<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>


<?php if($embedded):?>
<h4 class="blocktoggle amirodoc dotted" data-block="amirodoc">Амиро.CMS</h4>
<?php endif?>
<div class="correctwidth">
<div class="amirodoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="amirodoc">
        Амиро.CMS
    </<?=$h?>>
<hr  class="delimiter"/>
    <div>
        <h3>Автор</h3>
        <p>Веб-студия "Угол зрения" (<a href="http://www.ugolzreniya.ru">http://www.ugolzreniya.ru</a>)</p>
    </div>

    <div>
        <h3>Описание</h3>
        <noindex>
            <a href="http://www.ugolzreniya.ru/novosti/novye-moduli-geotargetirovanija">http://www.ugolzreniya.ru/novosti/novye-moduli-geotargetirovanija</a>
        </noindex>
    </div>

    <h3>
        <noindex>
            <a href="http://www.ugolzreniya.ru/moduli-amirocms/modules/eshop/order/geotargeting">http://www.ugolzreniya.ru/moduli-amirocms/modules/eshop/order/geotargeting</a>
        </noindex>
        <br>
        <noindex>
            <a href="http://www.ugolzreniya.ru/moduli-amirocms/modules/eshop/order/zapolnenie-adresov">http://www.ugolzreniya.ru/moduli-amirocms/modules/eshop/order/zapolnenie-adresov</a>
        </noindex>
    </h3>

<?php if($embedded):?><a href="amiro/">Amiro CMS</a><?php endif?>
</div>
</div>