<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>
<?php if($embedded):?>
<h4 class="blocktoggle bitrix2doc dotted" data-block="bitrix2doc">1С-Битрикс (2)</h4>
<?php endif?>
<div class="correctwidth">
<div class="bitrix2doc docblock" style="<?=$style?>">
    <a name="bitrix2"></a>

    <<?=$h?> class="blocktoggle dotted" data-block="bitrix2doc">
        1С-Битрикс
    </<?=$h?>>
    <hr  class="delimiter"/>
                <ul>
		    <li>   <noindex><a href="http://marketplace.1c-bitrix.ru/solutions/ipol.kladr/">Скачать в «Маркетплейсе»</a></noindex></li>
                </ul>

    <h3>Описание</h3>
    <p>Автозаполнение адреса доставки по КЛАДР. Разработано компанией-партнером «Ипол»</p>
    <p>Компания «Ипол» основана в 1991 году. Специализируется на разработке и реализации интернет-стратегий и разработке ПО. За годы работы выполнено множество проектов для компаний из различных сфер бизнеса, государственных структур, СМИ, информационных </p>


    <?php if($embedded):?><a href="bitrix2/">Bitrix (2)</a><?php endif?>



</div>
</div>

