<?php
$h = $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?php if ($embedded): ?>
    <h4 class="blocktoggle apidoc dotted" data-block="apidoc">Документация API сервиса</h4>

<?php endif ?>
<div class="correctwidth">
    <div class="apidoc docblock">
	<a name="json"></a>

	<h2 class="blocktoggle dotted" data-block="apidoc">Документация API сервиса</h2>
	<hr  class="delimiter"/>

	<p>Доступ к API является публичным и бесплатным без каких-либо ограничений. Публичные сервера предоставляются как есть, мы не гарантируем их работоспособность и скорость ответа. Публичный API отлично подходит, например, 
	для тестирования сервиса, личного использования, домашних страниц. Для бизнеса мы предлагаем <a href="/business/">платные сервера</a>, мы гарантируем, что они работают всегда быстро и стабильно. Доступ к платным серверам возможен только при указании специального токены, который мы высылаем после оплаты.</p>
        <h3>Параметры запроса</h3>
        <p>Адрес страницы для запроса: <noindex><a href="http://kladr-api.ru/api.php">http://kladr-api.ru/api.php</a></p></noindex>
	<p>Адрес страницы для запроса платных токенов: <noindex><a href="http://kladr-api.com/api.php">http://kladr-api.com/api.php</a></p></noindex>
        <b>Список доступных параметров запроса:</b>
        <ul>
            <li><code>token</code> — (необязательно) Токен для доступа к сервису. Используется только для доступа к <a href="/business/">платным серверам</a></li>
            <li><code>regionId</code> — Код региона (области)</li>
            <li><code>districtId</code> — Код района</li>
            <li><code>cityId</code> — Код города (населённого пункта)</li>
            <li><code>streetId</code> — Код улицы</li>
            <li><code>buildingId</code> — Код дома (строения)</li>
            <li><code>query</code> — Строка для поиска по названию</li>
            <li><code>contentType</code> — Тип возвращаемых объектов (region, district, city, street, building)</li>
            <li><code>withParent</code> — Если 1, сервис вернёт объекты вместе с родительскими (для района это регион, для населённого пункта район и регион и т.п.)</li>
            <li><code>limit</code> — Количество возвращаемых объектов</li>
	    <li><code>offset</code> — Смещение в выдаче (для организации постраничного вывода)</li>

	    <li><code>typeCode</code> — Тип объектов для выдачи:
		<ul>
		    <li>1 — города</li>
		    <li>2 — поселки</li>
		    <li>4 — деревни</li>
		    <li>Битовые комбинации, например, 3 ( 1 | 2 ) — города и поселки</li>
		</ul>
	    </li>

	    <li><code>zip</code> — Почтовый индекс. Работает только при contentType = building. В этом случае можно не передать parentId. Поиск по почтовому индексу — это поиск по строениям (building), поэтому логично указать withParent = 1 и limit = 1, чтоб выбрать данные о регионе, нас. пункте и т.п. 
		<br>Например: <a href="http://kladr-api.ru/api.php?contentType=building&limit=1&withParent=1&zip=163000">http://kladr-api.ru/api.php?contentType=building&limit=1&withParent=1&zip=163000</a></li>

	    <li><code>oneString</code> — Поиск адреса одной строкой в свободной форме. С этим параметром используются:
		<ul>
		    <li>query — строка поиска</li>
		    <li>withParent=1 — выводить сведения о родителях</li>
		    <li>limit — кол-во результатов в выдаче</li>
		    <li>regionId, districtId, cityId — фильтры для ограничения поиск</li>
		</ul>	  
		
		Например: <a href="http://kladr-api.ru/api.php?query=%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&oneString=1&limit=1&withParent=1">http://kladr-api.ru/api.php?query=%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&oneString=1&limit=1&withParent=1</a>
	    </li>

            <li><code>callback</code> – JavaScript метод которому будет передан ответ базы</li>
        </ul>

	<div>
	    <h3>Формат ответа сервиса</h3>
	    <p>Пример ответа сервиса:</p>
	    <p>Запрос: <noindex><a href="http://kladr-api.ru/api.php?query=%D0%90%D1%80%D1%85&contentType=city&withParent=1&limit=2" target="_blank">http://kladr-api.ru/api.php?query=Арх&contentType=city&withParent=1&limit=2</a></noindex></p>
	    <p>Ответ:</p>
	    <pre class="brush: js;">
{
    "searchContext": {                      // Объект с переданными серверу параметрами
        "query": "Арх",
        "contentType": "city",
        "withParent": 1,
        "limit": 2
    },
    "result": [                             // Массив полученных объектов заданного типа (населённые пункты)
        {
            "id": "2900000100000",          // Код объекта
            "name": "Архангельск",          // Название объекта
            "zip": null,                    // Почтовый индекс объекта
            "type": "Город",                // Тип объекта полностью
            "typeShort": "г",               // Тип объекта коротко
            "okato": "11401000000",         // Код ОКАТО
            "parents": [                    // Массив родительских объектов (если был передан параметр withParent)
                {
                    "id": "2900000000000",
                    "name": "Архангельская",
                    "zip": null,
                    "type": "Область",
                    "typeShort": "обл",
                    "okato": "11000000000",
		    "contentType": "region"
                }
            ]
        },
        {
            "id": "2800200000100",
            "name": "Архара",
            "zip": "676740",
            "type": "Поселок городского типа",
            "typeShort": "пгт",
            "okato": "10205551000",
            "parents": [
                {
                    "id": "2800000000000",
                    "name": "Амурская",
                    "zip": "675000",
                    "type": "Область",
                    "typeShort": "обл",
                    "okato": "10000000000",
		    "contentType": "region"
                },
                {
                    "id": "2800200000000",
                    "name": "Архаринский",
                    "zip": null,
                    "type": "Район",
                    "typeShort": "р-н",
                    "okato": "10205000000",
		    "contentType": "district"
                }
            ]
        }
    ]
}   
	    </pre>
	</div>

	<div>
	    <h3>Особенности поиска объектов</h3>
	    <p>
		Поиск объектов осуществляется либо по названию либо по коду связанного (родительского либо дочернего элемента).
		Поиск объектов по названию осуществляется по шаблону /^название/ (т.е. выбираются объекты, название которых полностью
		совпадает с поисковой строкой либо начинается на неё).
		<br><br>
		Для поиска улицы по названию необходимо обязательно указать код населённого пункта, например <noindex><a href="http://kladr-api.ru/api.php?cityId=7800000000000&query=3&contentType=street&limit=50" target="_blank">cityId=7800000000000&query=3&contentType=street</a></noindex>.
            <br>
            Для поиска строения по названию необходимо обязательно указать код улицы, например <noindex><a href="http://kladr-api.ru/api.php?streetId=29000001000025800&query=1&contentType=building&limit=50" target="_blank">streetId=29000001000025800&query=1&contentType=building</a></noindex>.
	    </p>
	</div>
    </div>
</div>
