<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?php if($embedded):?>
<h4 class="blocktoggle drupaldoc dotted" data-block="drupaldoc">Drupal</h4>
<?php endif?>

<div class="correctwidth">
<div class="drupaldoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="drupaldoc">
        Drupal
    </<?=$h?>>
<hr  class="delimiter"/>
    <div>
        <h3>Автор</h3>
        <p>
            <noindex><a href="http://saitovik.com/">http://saitovik.com/</a></noindex></p>
    </div>

    <h3>
        <noindex>
            <a href="http://www.drupal.ru/node/109027">http://www.drupal.ru/node/109027</a>
        </noindex>
    </<?=$h?>>

    <?php if($embedded):?><a href="drupal/">Drupal</a><?php endif?>
</div>
</div>