<link type="text/css" rel="stylesheet" href="/js/highlight/styles/shCoreDefault.css"/>

<script type="text/javascript" src="/js/highlight/scripts/shCore.js"></script>
<script type="text/javascript" src="/js/highlight/scripts/shBrushJScript.js"></script>
<script type="text/javascript">
    SyntaxHighlighter.all();
    $(function () {
        $('.blocktoggle').click(function () {
            var el = '.' + $(this).data('block');
            $(el).toggle();
        });
    })

</script>


<div class="content">
    <div class="cBlock">
	<div class="contentNav">
	    <h4><a href="/business">Облако для бизнеса</a></h4>
	    <h4><a href="/business#box">Коробочная версия</a></h4>
	    <h4><a href="/forum">Форум</a></h4>
	    <h4><a href="/prices#faq">Частые вопросы</a></h4>


	    <h4><a href="https://trello.com/b/NlSSs2UV/-">Trello</a></h4>
	    <h4><a href="https://twitter.com/kladrapi">Наш твиттер</a></h4>
	    <?php if (false) foreach ($parts as $key => $name): ?>
		    <h4><?= $name[0] ?></h4>
		<?php endforeach ?>

	</div>
	<div class="contentMain">
	    <h1>Интеграция</h1>
	    <h3>Возможности</h3>
	    <p>Сервис предоставляет он-лайн интерфейс к базе адресов Российской Федерации(«ФИАС»). Обмен данными
		происходит в формате JSON, с поддержкой JSONP.</p>
	    <p>Для облегчнения интеграции разработаны плагины под разные плаформы, которые подробно описаны ниже
		на этой странице. Плагины распространяются бесплатно под лицензией «Public domain», без каких-либо
		ограничений на использование.</p>
	    <p>Основные возможности:</p>
	    <ul>
		<li>Искать регионы, нас. пункты, улицы, дома по подстроке и по коду</li>
		<li>Фильтровать данные по регионам, нас. пунткам и улицам</li>
		<li>Получать сведения о родительских элементах и почтовых индексах</li>
	    </ul>
	    <p>Например, можно попросить сервис вернуть все города на букву «А», или все улицы Москвы начинающиеся
		на «Лен».</p>
	    <h3>Исходные коды</h3>
	    <p>Все исходные коды сервиса доступны в <a href="https://github.com/garakh/kladrapi">открытом виде</a>.
		Вы можете <a href="https://trello.com/b/NlSSs2UV/-"> принять участие в разработке проекта.</a></p>

	    <h3>А у кого можно спросить?</h3>
	    <p>
		Напишите нам на <a href="mailto:info@kladr-api.ru">info@kladr-api.ru</a>.
	    </p>
	    <div class="dropWrap">
		<?php foreach ($parts as $key => $name): ?>
		    <?php $this->partial("integration/" . $key, array('embedded' => true)); ?>
		<?php endforeach ?>
	    </div>
	</div>
    </div>
</div>










