<div class="otherheader">
    <h1>Интеграция</h1>
</div>

<link type="text/css" rel="stylesheet" href="/js/highlight/styles/shCoreDefault.css"/>

<script type="text/javascript" src="/js/highlight/scripts/shCore.js"></script>
<script type="text/javascript" src="/js/highlight/scripts/shBrushJScript.js"></script>
<script type="text/javascript">SyntaxHighlighter.all();</script>
	
<div class="correctwidth">
    <div class="content">
        <div class="document">
            <div class="table-contents">
                <ul>
                    <li><a href="#json">Документация API сервиса</a></li>
                    <li><a href="#jquery">jQuery plugin</a></li>
                    <li><a href="#net">.NET provider</a></li>
                    <li><a href="#php">PHP API</a></li>
                    <li><a href="#bitrix">Модуль для 1С-Битрикс</a></li>
                </ul>
            </div>
            
			<div>
				<h2>Возможности</h2>
				<p>Сервис предоставляет он-лайн интерфейс к базе адресов Российской Федерации(«ФИАС»). Обмен данными происходит в формате JSON, с поддержкой JSONP.</p>
				<p>Для облегчнения интеграции разработаны плагины под разные плаформы, которые подробно описаны ниже на этой странице. Плагины распространяются бесплатно под лицензией «Public domain», без каких-либо ограничений на использование.
				</p>
				<p>
					Основные возможности:
				</p>
				<ul>
					<li>Искать регионы, нас. пункты, улицы, дома по подстроке и по коду</li>
					<li>Фильтровать данные по регионам, нас. пунткам и улицам</li>
					<li>Получать сведения о родительских элементах и почтовых индексах</li>
				</ul>				
				
				<p>Например, можно попросить сервис вернуть все города на букву «А», или все улицы Москвы начинающиеся на «Лен».</p>
				<h2>Исходные коды</h2>
				<p>Все исходные коды сервиса доступны в <a href="https://github.com/garakh/kladrapi">открытом виде</a>. Вы можете <a href="https://trello.com/b/NlSSs2UV/-"> принять участие в разработке проекта.</a>
				</p>
			</div>
			<hr class="delimiter"/>
			
            <div>
                <a name="json"></a>
                
                <h2>Документация API сервиса</h2>

				<p>Для работы с сервисом Вам понадобится один из ключей:</p>
				<ul>
					<li>Ключ с привязкой к домену</li>
					<li>Ключ <i>без</i> привязки к домену</li>
				</ul>
				<p>Используйте ключ с привязкой к домену на Вашем сайте в формах ввода информации. Ключ без привязки к домену стоит использовать в Ваших серверных приложениях.
				</p>
				<p>Во всех примерах на этой странице используется <b>демонстрационный ключ</b>, который периодически меняется. Не используйте его в своих рабочих приложениях.</p>
                <div>
                    <h3>Параметры запроса</h3>
                    <p>Адрес страницы для запроса: <noindex><a href="http://kladr-api.ru/api.php">http://kladr-api.ru/api.php</a></p></noindex>
                    <h5>Список доступных параметров запроса:</h5>
                    <ol>
                        <li><code>token</code> – Токен для доступа к сервису</li>
                        <li><code>key</code> – Ключ для доступа к сервису</li>
                        <li><code>regionId</code> – Код региона (области)</li>
                        <li><code>districtId</code> – Код района</li>
                        <li><code>cityId</code> – Код города (населённого пункта)</li>
                        <li><code>streetId</code> – Код улицы</li>
                        <li><code>buildingId</code> – Код дома (строения)</li>
                        <li><code>query</code> – Строка для поиска по названию</li>
                        <li><code>contentType</code> – Тип возвращаемых объектов (region, district, city, street, building)</li>
                        <li><code>withParent</code> – Если 1, сервис вернёт объекты вместе с родительскими (для района это регион, для населённого пункта район и регион и т.п.)</li>
                        <li><code>limit</code> – Количество возвращаемых объектов</li>
                        <li><code>callback</code> – JavaScript метод которому будет передан ответ базы</li>
                    </ol>
                </div>
                
                <div>
                    <h3>Формат ответа сервиса</h3>
                    <p>Пример ответа сервиса:</p>
                    <p>Запрос: <noindex><a href="http://kladr-api.ru/api.php?query=%D0%90%D1%80%D1%85&contentType=city&withParent=1&limit=2&token=51dfe5d42fb2b43e3300006e&key=86a2c2a06f1b2451a87d05512cc2c3edfdf41969" target="_blank">http://kladr-api.ru/api.php?query=Арх&contentType=city&withParent=1&limit=2&token=51dfe5d42fb2b43e3300006e &key=86a2c2a06f1b2451a87d05512cc2c3edfdf41969</a></noindex></p>
                    <p>Ответ:</p>
                    <pre class="brush: js;">
{
    "searchContext": {                      // Объект с переданными серверу параметрами
        "query": "Арх",
        "contentType": "city",
        "withParent": 1,
        "limit": 2
    },
    "result": [                             // Массив полученных объектов заданного типа (населённые пункты)
        {
            "id": "2900000100000",          // Код объекта
            "name": "Архангельск",          // Название объекта
            "zip": null,                    // Почтовый индекс объекта
            "type": "Город",                // Тип объекта полностью
            "typeShort": "г",               // Тип объекта коротко
            "okato": "11401000000",         // Код ОКАТО
            "parents": [                    // Массив родительских объектов (если был передан параметр withParent)
                {
                    "id": "2900000000000",
                    "name": "Архангельская",
                    "zip": null,
                    "type": "Область",
                    "typeShort": "обл",
                    "okato": "11000000000",
                }
            ]
        },
        {
            "id": "2800200000100",
            "name": "Архара",
            "zip": "676740",
            "type": "Поселок городского типа",
            "typeShort": "пгт",
            "okato": "10205551000",
            "parents": [
                {
                    "id": "2800000000000",
                    "name": "Амурская",
                    "zip": "675000",
                    "type": "Область",
                    "typeShort": "обл",
                    "okato": "10000000000",
                },
                {
                    "id": "2800200000000",
                    "name": "Архаринский",
                    "zip": null,
                    "type": "Район",
                    "typeShort": "р-н",
                    "okato": "10205000000",
                }
            ]
        }
    ]
}   
                    </pre>
                </div>

                <div>
                    <h3>Особенности поиска объектов</h3>
                    <p>
                        Поиск объектов осуществляется либо по названию либо по коду связанного (родительского либо дочернего элемента). 
                        Поиск объектов по названию осуществляется по шаблону /^название/ (т.е. выбираются объекты, название которых полностью 
                        совпадает с поисковой строкой либо начинается на неё).
                        <br><br>
                        Для поиска улицы по названию необходимо обязательно указать код населённого пункта, например <noindex><a href="http://kladr-api.ru/api.php?token=51dfe5d42fb2b43e3300006e&key=86a2c2a06f1b2451a87d05512cc2c3edfdf41969&cityId=7800000000000&query=3&contentType=street&limit=50" target="_blank">cityId=7800000000000&query=3&contentType=street</a></noindex>.
                        <br>
                        Для поиска строения по названию необходимо обязательно указать код улицы, например <noindex><a href="http://kladr-api.ru/api.php?&token=51dfe5d42fb2b43e3300006e&key=86a2c2a06f1b2451a87d05512cc2c3edfdf41969&streetId=29000001000025800&query=1&contentType=building&limit=50" target="_blank">streetId=29000001000025800&query=1&contentType=building</a></noindex>.
                    </p>
                </div>
            </div>
			<hr class="delimiter"/>
            
            <div>
                <a name="jquery"></a>
                
                <h2>
                    jQuery plugin
                    <noindex><a href="https://github.com/garakh/kladrapi-jsclient/zipball/master">&#8595;ZIP</a></noindex>
                    <noindex><a href="https://github.com/garakh/kladrapi-jsclient/tarball/master">&#8595;TAR</a></noindex>
                </h2>   
                
                <div>
                    <h3>Архитектура</h3>                    
                    <ul>
                        <li><code>$.kladr</code> - (статичный объект) предоставляет методы и свойства для работы с сервисом</li>
                        <li><code>$( "selector" ).kladr</code> - (плагин jQuery) плагин для автодополнения адреса</li>
                    </ul>
                    
                    <p>Подключение</p>
                    <pre class="brush: js;">
$( 'input' ).kladr({
    option1: 'value1',
    option2: 'value2'
});
                    </pre>
                    
                    <p>Чтение опции, свойства</p>
                    <pre class="brush: js;">
$( 'input' ).kladr('option1');
                    </pre>
                    
                    <p>Изменение опции, свойства</p>
                    <pre class="brush: js;">
$( 'input' ).kladr('option1', 123);
                    </pre>
                </div>
                
                <div>
                    <h3>Свойства объекта $.kladr</h3>                    
                    <ul>
                        <li><code>url</code> - url сервиса, по-умолчанию <noindex><a href="https://kladr-api.ru/api.php">https://kladr-api.ru/api.php</a></noindex></li>
                        <li><code>type</code> - перечисление используемых типов объектов. Список значений: <code>region, district, city, street, building</code></li>
                        <li><code>api</code> <code>= function( query, callback ) {}</code> - функция непосредственно выполняющая запрос к сервису. В качестве параметров принимает объект запроса и функцию, которой будет передан ответ сервиса.</li>
                        <li><code>check</code> <code>= function( query, callback ) {}</code> - функция для проверки существования объекта. В качестве параметров принимает объект запроса и функцию, которой будет передан объект (если он существует) либо false</li>
                    </ul>
                </div>

                <div>
                    <h3>Параметры плагина</h3>                    
                    <ul>
                        <li><code>token</code> - токен для доступа к сервису, обязательный параметр</li>
                        <li><code>key</code> – ключ для доступа к сервису, обязательный параметр</li>
                        <li><code>type</code> – тип подставляемых объектов, обязательный параметр</li>
                        <li><code>parentType</code> – тип родительского объекта, по-умолчанию <code>null</code></li>
                        <li><code>parentId</code> - идентификатор родительского объекта, по-умолчанию <code>null</code></li>
                        <li><code>limit</code> - количество отображаемых в выпадающем списке объектов, по-умолчанию <code>10</code></li>
                        <li><code>withParents</code> - получить объект вместе с родителями, по-умолчанию <code>false</code></li>
                        <li><code>showSpinner</code> - отображать ajax-крутилку, по-умолчанию <code>true</code></li>
                        <li><code>verify</code> - проверять введённые данные, по-умолчанию <code>false</code></li>
                        <li><code>current</code> - текущий, выбранный объект КЛАДР</li>
                    </ul>
                </div>
                
                <div>
                    <h3>Методы плагина</h3>                    
                    <ul>
                        <li><code>source = function( query ) { return objects; }</code> - функция для получения списка объектов отображаемых при автодополнении. По-умолчанию запрашивает данные у сервиса. Может быть переопределена для получения объектов из другого источника.</li>
                        <li><code>labelFormat = function( obj, query) { return label; }</code> - функция для форматирования значений в списке. В качестве параметров принимает <code>obj</code> – объект КЛАДР, <code>query</code> – текущее значение поля ввода.</li>
                        <li><code>valueFormat = function( obj, query) { return label; }</code> – функция для форматирования подставляемых в поле ввода значений. В качестве параметров принимает <code>obj</code> – объект КЛАДР, <code>query</code> – текущее значение поля ввода.</li>
                    </ul>
                </div>
                
                <div>
                    <h3>События плагина</h3>                    
                    <ul>
                        <li><code>open = function() {}</code> - открыт список объектов. Доступно как событие <code>kladr_open</code> поля ввода.</li>
                        <li><code>close = function() {}</code> - закрыт список объектов. Доступно как событие <code>kladr_close</code> поля ввода.</li>
                        <li><code>send = function() {}</code> - отправлен запрос к сервису. Доступно как событие <code>kladr_send</code> поля ввода.</li>
                        <li><code>received = function() {}</code> - получен ответ от сервиса. Доступно как событие <code>kladr_received</code> поля ввода.</li>
                        <li><code>select = function( obj ) {}</code> - выбран объект в списке. В параметре передаётся текущий, выбранный объект КЛАДР. Доступно как событие <code>kladr_select</code> поля ввода.</li>
                        <li><code>check = function( obj ) {}</code> - проверен введённый пользователем объект. Вызывается только если параметр <code>verify = true</code>. В параметре передаётся текущий объект КЛАДР. Доступно как событие <code>kladr_check</code> поля ввода.</li>
                    </ul>
                </div>
                
                <div>
                    <h3>Примеры</h3>    
                    
                    <p>Автодополнение городами России</p>
                    <pre class="brush: js;">
$( 'input' ).kladr({
    token: 'token',
    key: 'key',
    type: $.kladr.type.city
});
                    </pre>
                    
                    <p>Изменении подписи при выборе района</p>
                    <pre class="brush: js;">
$( 'input' ).kladr({
    token: 'token',
    key: 'key',
    type: $.kladr.type.district,
    select: function( obj ){
        $( 'label' ).text( obj.type );
    }
});
                    </pre>
                    
                    <p>Проверка названия города, введённого пользователем самостоятельно</p>
                    <pre class="brush: js;">
$( 'input' ).kladr({
    token: 'token',
    key: 'key',
    type: $.kladr.type.city,
    check:  function( obj ){
        if(obj){
            $( 'input' ).css('color', 'black');
        } else {
            $( 'input' ).css('color', 'red');
        }
    }
});
                    </pre>
                </div>
            </div>
                        
            <hr  class="delimiter"/>
			
            <div>
                <a name="net"></a>
                
                <h2>
                    .NET provider
                    <noindex><a href="https://github.com/garakh/kladrapi-dotnet/zipball/master">&#8595;ZIP</a></noindex>
                    <noindex><a href="https://github.com/garakh/kladrapi-dotnet/tarball/master">&#8595;TAR</a></noindex>
                </h2>
                
                <div>
                    <h3>Автор</h3>
                    <p>Антон Губаренко (<a href="https://github.com/lanserxt">github</a>)</p>
                </div>
                
                <div>
                    <h3>Описание</h3>
                    <p>Представляет собой DLL, которую можно подключить в References для осуществления поиска aдреса в Кладр.</p>
                </div>
                
                <div>
                    <h3>Использование</h3>
                    <ol>
                        <li>Скопировать <code>KladrApiClient.dll</code> и <code>Newtonsoft.Json.Net20.dll</code> в папку с Вашим проектом (или сделать свою сборку с помощью исходниклв в папке Sources)</li>
                        <li>Добавить их в <code>References</code></li>
                        <li>Указать <code>using KladrApiClient;</code> в классе</li>
                        <li>Создать объект класса <code>KladrClient</code></li>
                        <li>Осуществить поиск с помощью метода <code>FindAddress</code>, которые принимает параметры запроса в формате <code>Dictionary</code></li>
                    </ol>
                    <h5>Список возможных параметров:</h5>
                    <ul>
                        <li><code>token</code> – токен для доступа к сервису</li>
                        <li><code>key</code> – ключ для доступа к сервису</li>
                        <li><code>regionId</code> – код родительского региона</li>
                        <li><code>districtId</code> – код района</li>
                        <li><code>cityId</code> – код города</li>
                        <li><code>streetId</code> – код улицы</li>
                        <li><code>buildingId</code> – код строения</li>
                        <li><code>query</code> – строка для поиска по названию</li>
                        <li><code>contentType</code> – тип объекта для поиска</li>
                        <li><code>withParent</code> – вернуть объекты вместе с родителями, если 1 то в каждый объект будет добавлено поле parents содержащее список объектов-родителей объекта</li>
                        <li><code>limit</code> – ограничение количества возвращаемых объектов, по умолчанию = 2000</li>
                    </ul>                    
                </div>
                
                <div>
                    <h3>Пример</h3>
                    
                    <pre class="brush: js;">
using KladrApiClient; 
using System; 
using System.Collections.Generic; 
using System.Windows;

public partial class MainWindow : Window
{
    private KladrClient kladrClient;
    public MainWindow()
    {
        InitializeComponent();
        kladrClient = new KladrClient("some_token", "some_key");
    }

    private void Button_Click(object sender, RoutedEventArgs e)
    {
        kladrClient.FindAddress(new Dictionary&lt;string, string&gt;
                                    {
                                        {"query", "Арх"},
                                        {"contentType", "city"},
                                        {"withParent", "1"},
                                        {"limit", "2"}
                                    }, fetchedAddress);
    }

    private void fetchedAddress(KladrResponse response)
    {
        if(response!=null)
        {
            if (response.result != null && response.InfoMessage.Equals("OK"))
                MessageBox.Show(string.Format("Found {0} results", response.result.Length));
        }
    }
}
                    </pre>
                </div>
            </div>	
            
            <hr  class="delimiter"/>
            
            <div>
                <a name="php"></a>
                
                <h2>
                    PHP API
                    <noindex><a href="https://github.com/garakh/kladrapi-php/zipball/master">&#8595;ZIP</a></noindex>
                    <noindex><a href="https://github.com/garakh/kladrapi-php/tarball/master">&#8595;TAR</a></noindex>
                </h2>
                
               
                <div>
                    <h3>Описание API</h3>
                    
                    <div>
                        <h4>Kladr\Api</h4>
                        <p>Контроллер доступа к сервису</p>
                        
                        <h5>Функции</h5>
                        <ul>
                            <li><code>QueryToJson(Query $query)</code> - выполняет запрос к сервису, возвращая данные в виде объекта Json</li>
                            <li><code>QueryToArray(Query $query)</code> - выполняет запрос к сервису, возвращая данные в виде ассоциативного массива</li>
                            <li><code>QueryToObjects(Query $query)</code> - выполняет запрос к сервису, возвращая данные в виде массива объектов</li>
                        </ul>
                        
                        <h5>Свойства</h5>
                        <ul>
                            <li><code>Error</code> - текст последней, возникшей при обращении к сервису, ошибки</li>
                        </ul>
                    </div>
                    
                    <div>
                        <h4>Kladr\Query</h4>
                        <p>Объект запроса</p>
                        
                        <h5>Свойства</h5>
                        <ul>
                            <li><code>ParentType</code> - тип родительского объекта для ограничения области поиска (регион, район, город)</li>
                            <li><code>ParentId</code> - идентификатор родительского объекта для ограничения области поиска</li>
                            <li><code>ContentType</code> - тип искомого объекта (регион, район, город)</li>
                            <li><code>ContentName</code> - название искомого объекта</li>
                            <li><code>WithParent</code> - получить объекты вместе с родителями (если true у объекта заполняется свойство Parent)</li>
                            <li><code>Limit</code> - ограничение количества возвращаемых объектов</li>
                        </ul>
                    </div>
                    
                    <div>
                        <h4>Kladr\Object</h4>
                        <p>Объект базы</p>
                        
                        <h5>Свойства</h5>
                        <ul>
                            <li><code>Id</code> - идентификатор объекта</li>
                            <li><code>Name</code> - название объекта</li>
                            <li><code>Zip</code> - почтовый индекс объекта</li>
                            <li><code>Type</code> - подпись объекта полностью (область, район)</li>
                            <li><code>TypeShort</code> - подпись объекта коротко (обл, р-н)</li>
                            <li><code>Parents</code> - массив родительских объектов (заполняется если в запросе был установлен флаг WithParent)</li>
                        </ul>
                    </div>
                    
                    <div>
                        <h4>Kladr\ObjectType</h4>
                        <p>Перечисление типов  объектов, используемых в запросах к сервису</p>
                        
                        <h5>Константы</h5>
                        <ul>
                            <li><code>Region</code> - регион</li>
                            <li><code>District</code> - район</li>
                            <li><code>City</code> - населённый пункт</li>
                            <li><code>Street</code> - улица</li>
                            <li><code>Building</code> - строение</li>
                        </ul>
                    </div>
                </div>
                
                <div>
                    <h3>Примеры</h3>
                    
                    <p>Получение списка всех населённый пунктов, название которых начинается на "Арх"</p>
                    <pre class="brush: js;">
// Инициализация api, в качестве параметров указываем токен и ключ для доступа к сервису
$api = new Kladr\Api('51dfe5d42fb2b43e3300006e', '86a2c2a06f1b2451a87d05512cc2c3edfdf41969');

// Формирование запроса
$query = new Kladr\Query();
$query->ContentName = 'Арх';
$query->ContentType = Kladr\ObjectType::City;
$query->WithParent = true;
$query->Limit = 2;

// Получение данных в виде ассоциативного массива
$arResult = $api->QueryToArray($query);
                    </pre>
                </div>
            </div>
            <hr  class="delimiter"/>
			
            <div>
                <a name="bitrix"></a>
                
                <h2>
                    Модуль "КЛАДР в облаке" для 1С-Битрикс
                    <noindex><a href="https://github.com/garakh/kladr-bitrix/zipball/master">&#8595;ZIP</a></noindex>
                    <noindex><a href="https://github.com/garakh/kladr-bitrix/tarball/master">&#8595;TAR</a></noindex>
                </h2>
                
                <p>Модуль 1С-Битрикс предоставляющий форму для ввода адреса с автодополнением. В качестве источника данных используется сервис «КЛАДР в облаке»</p>
                <img src="/public/content/kladr-bitrix1.png">
                
                <div>
                    <h3>Установка</h3>                    
                    <ol>
                        <li>Загрузите модуль</li>
                        <li>Скопируйте в папку «/bitrix/modules»  вашего сайта</li>
                        <li>Переименуйте модуль в primepixkladr</li>
                        <li>Установите модуль <img src="/public/content/kladr-bitrix2.png"></li>
                        <li>Разместите компонент «Форма для ввода адреса» на странице для ввода адреса <img src="/public/content/kladr-bitrix3.png"></li>
                        <li>В настройках компонента укажите токен и ключ для подключения к сервису «КЛАДР в облаке» <img src="/public/content/kladr-bitrix4.png"></li>
                        <li>Пользуйтесь =)</li>
                    </ol>
                </div>
                
                <div>
                    <h3>Параметры компонента «Форма для ввода адреса»</h3>
                    <ol>
                        <li>
                            Основные параметры
                            <ol>
                                <li><code>Токен для доступа к КЛАДР API</code> - токен для доступа к сервису</li>
                                <li><code>Ключ для доступа к КЛАДР API</code> - ключ для доступа к сервису</li>
                            </ol>
                        </li>
                        <li>
                            Выводить поля для ввода
                            <ol>
                                <li><code>Области</code> – Добавляет поле с именем «region» для ввода названия области</li>
                                <li><code>Района</code> – Добавляет поле с именем «district» для ввода названия района</li>
                                <li><code>Населённого пункта</code> – Добавляет поле c именем «location» для ввода названия населённого пункта</li>
                                <li><code>Улицы</code> – Добавляет поле c именем «street» для ввода названия улицы</li>
                                <li><code>Дома</code> – Добавляет поле с именем «building» для ввода номера дома</li>
                            </ol>
                        </li>
                        <li>
                            Выводить скрытые поля
                            <ol>
                                <li><code>Код объекта</code> – добавляет скрытое поле с именем «kladr_id», в которое по окончанию ввода адреса будет записан его код</li>
                                <li><code>Почтовый индекс</code> – добавляет скрытое поле с именем «zip_code» в которое по окончанию ввода адреса будет записан его почтовый индекс из КЛАДР</li>
                                <li><code>Подписи</code> – добавляет скрытое поле с постфиксом «_label» к каждому полю ввода в которое будет записана подпись к введённому пользователем значению (например: город, посёлок, село)</li>
                                <li><code>Сокращения подписей</code> – добавляет скрытое поле к постфиксом «_label_min» к каждому полю ввода, в которое будет записано сокращение подписи к введённому пользователем значению (г., пос., с.)</li>
                            </ol>
                        </li>
                        <li>
                            Опции
                            <ol>
                                <li><code>Обновлять подписи при вводе</code> – Включает обновление подписей к полям ввода. Например, если пользователь в поле город введёт «Москва», то подпись «Населённый пункт» автоматически будет изменена на «Город»</li>
                                <li><code>Удалять значения, которых нет в КЛАДР</code> – Включает проверку ввода в поля адреса и удаление ошибочно введённых значений. Например, если пользователь введёт в поле «Населённый пункт» значение «Мухосранск», то оно будет автоматически удалено, т.к. населённого пункта «Мухосранск» в России нет.</li>
                            </ol>
                        </li>
                        <li>
                            Дополнительные параметры
                            <ol>
                                <li><code>Подключить jQuery</code> – Компонент использует библиотеку jQuery, поэтому если она не используется у вас на сайте включите данный пункт</li>
                                <li><code>Подключить jQuery UI</code> – Компонент использует библиотеку jQuery UI, поэтому если она не используется у вас на сайте включите данный пункт</li>
                                <li><code>Подключить тему jQuery UI</code> – Компонент использует тему jQuery UI для автодополнения адреса. Если она не используется у вас на сайте включите данный пункт</li>
                            </ol>
                        </li>
                    </ol>
                </div>
                
                <div>
                    <h3>Результат</h3>
                    <p>
                        Компонент выводит на сайт несколько текстовых и скрытых полей для ввода адреса. Компонент не генерирует формы (&lt;form&gt;&lt;/form&gt;) для отправки на сервер введённой пользователем информации! 
                        Это сделано для того чтобы вы без проблем могли включить поля для ввода адреса в любую другую существующую форму на вашем сайте (к примеру форму оформления заказа). 
                    </p>
                </div>
            </div>
			<hr  class="delimiter"/>			
        </div>        
    </div>      
</div>