<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?if($embedded):?>
<h2 class="blocktoggle nodejsdoc dotted" data-block="nodejsdoc">Node.js</h2>
<?endif?>
<div class="correctwidth">
<div class="nodejsdoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="nodejsdoc">
        Node.js
    </<?=$h?>>

    <div>
        <h3>Автор</h3>
        <p><a href="https://github.com/toporchillo">https://github.com/toporchillo</a></p>
    </div>

    <h3>
        <noindex>
            <a href="https://github.com/toporchillo/kladrapi-nodejs">https://github.com/toporchillo/kladrapi-nodejs</a>
        </noindex>
    </h3>
    <?if($embedded):?><a href="nodejs/">NodeJs</a><?endif?>
</div>
</div>
