<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?if($embedded):?>
<h4 class="blocktoggle nodejsdoc dotted" data-block="nodejsdoc">Node.js</h4>
<?endif?>
<div class="correctwidth">
<div class="nodejsdoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="nodejsdoc">
        Node.js
    </<?=$h?>>
    <hr  class="delimiter"/>


        <h3>Автор</h3>
        <p><noindex><a href="https://github.com/toporchillo">Githib</a></noindex></p>


    <p>
        <noindex>
           Документация рещения — <a href="https://github.com/toporchillo/kladrapi-nodejs">https://github.com/toporchillo/kladrapi-nodejs</a>
        </noindex>
    </p>
    <br><br>
    <?if($embedded):?><a href="nodejs/">NodeJs</a><?endif?>
</div>
</div>
