<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?php if($embedded):?>
<h4 class="blocktoggle onesdoc dotted" data-block="onesdoc">1C Предприятие 8.2</h4>
<?php endif?>

<div class="correctwidth">
<div class="onesdoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="onesdoc">
        1С Предприятие 8.2 КЛАДР (ФИАС)
    </<?=$h?>>
    <hr  class="delimiter"/>
        <h3>Автор</h3>
        <p>
            <noindex><a href="http://infostart.ru/profile/255262/">Профиль автора</a></noindex></p>

    <p>
        <noindex>
            Документация решения — <a href="http://infostart.ru/public/299231/">http://infostart.ru/public/299231/</a>
        </noindex>
    </p>
    <br><br>
    <?php if($embedded):?><a href="ones/">1С</a><?php endif?>
</div>
</div>