<?php
$h =  $embedded ? 'h2' : 'h1';
$style = $embedded ? 'display: none;' : '';
?>

<?if($embedded):?>
<h2 class="blocktoggle drupaldoc dotted" data-block="drupaldoc">1C Предприятие 8.2</h2>
<?endif?>

<div class="correctwidth">
<div class="drupaldoc docblock" style="<?=$style?>">

    <<?=$h?> class="blocktoggle dotted" data-block="drupaldoc">
        1С Предприятие 8.2 КЛАДР (ФИАС)
    </h2>

    <div>
        <h3>Автор</h3>
        <p>
            <noindex><a href="http://infostart.ru/profile/255262/">Профиль автора/</a></noindex></p>
    </div>

    <h3>
        <noindex>
            <a href="http://infostart.ru/public/299231/">http://infostart.ru/public/299231/</a>
        </noindex>
    </<?=$h?>>

    <?if($embedded):?><a href="ones/">1С</a><?endif?>
</div>
</div>