<?php

use \Phalcon\Tag ?>

<div class="content">
    <div class="cBlock" style="min-height: 500px;">
        <div class="contentMain">
            <h1>Сброс пароля</h1>
            <?php echo $this->getContent() ?>
            <?php if ($recovered): ?>
                <p style="text-align: center;">Новый пароль отправлен вам на email.</p>
                    <?php else: ?>
                <div class="form">
                    <form action="/recovery" method="post">      
    <?php echo Tag::textField(array("email", "id" => "inputEmail", "placeholder" => "Логин", "data-email" => "y")) ?>
                <?php echo Tag::submitButton(array('Сбросить пароль', "class" => "btn")) ?>
                    </form>
                </div>
<?php endif ?>
            <br><br>
            <a href="http://passwork.ru" target="_blank">
                <img src="https://passwork.me/b/passwork_02_ru.png" style="width: 200px; margin: 0px" >
            </a>            
        </div>
    </div>
</div>