<?php use Phalcon\Tag; ?>
<div class="otherheader">
    <h1><?= $user->email ?></h1>
</div>

<?= Tag::javascriptInclude('js/personal.js'); ?>

<div class="correctwidth">
    <div class="content">
        <p>Токен пользователя: <span><?= $user->_id ?></span></p>

        <p class="permanent-key">Ключ: <span id="permanent-key"><?= $user->key ?></span><a id="permanent-key-reload" href="">обновить</a></p>

        <p class="domain-key">Домен: <input id="domain" type="text" value="<?= $user->domain ?>">, ключ:<span id="domain-key"><?= $user->domainkey ?></span><a id="domain-key-reload" href="">обновить</a></p>

        <?php if(count($requests)): ?>
        <table class="table-bordered table-striped">
            <caption>Последние 100 запросов к сервису</caption>
            <thead>
                <tr>
                    <th>IP</th>
                    <th>Строка запроса</th>
                    <th>Время обращения</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($requests as $request): ?>
                <tr>
                    <td><?= $request->ip ?></td>
                    <td><?= $request->query ?></td>
                    <td><?= date('H:i:s d.m.Y', $request->time->sec); ?></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php endif ?>
    </div>
</div>