 <div class="header">
        <div class="cBlock rel">
            <div class="openSource" onclick="location='https://github.com/garakh/kladrapi'">
                <p>it's open source!</p>
            </div>
            <div class="logo">
                <a href="/"><img src="img/logo.png" alt="ФИАС и КЛАДР в облаке" /></a>
                <p>КЛАДР в облаке</p>
                <h3>Мы переработали базы адресов в простой и удобный сервиc.</h3>
                <h3>Работа с базой адресов стала легкой.</h3>
            </div>
            <div class="formWrap">
                <form>
                    <a href="/integration">Подключить сайт</a>
                </form>
            </div>
            <div class="formBg"></div>
        </div>
    </div>
    <div class="info">
        <p>Работая над своими проектами, мы столкнулись с задачей создания формы, где пользователь мог бы выбрать
            любой адрес России. Нам хотелось исключить ошибки при вводе, дать пользователю возможность выбирать из
            списка с подсказками всех населенных пунктов, регионов, улиц и даже домов.<br><br>
        Мы переработали базы адресов ФИАС в простой и удобный сервиc с откытым исходным кодом.
            </p>
    </div>
    <div class="benefits cBlock">
        <h2>ПРЕИМУЩЕСТВА СЕРВИСА</h2>
        <div class="benefitsWrap">
            <div class="westSide">
                <div class="desc trig1">
                   <h4>ЛЕГКАЯ ИНТЕГРАЦИЯ</h4>
                    <p>Доступ к базе через JSON<br> веб-сервис, .Net LINQ Provider, jQuery plugin, поддержка
                        популярных CMS, и другие виды интеграции.</p>
                </div>
            </div>
            <div class="eastSide">
                <div class="desc trig2">
                    <h4>ОБНОВЛЕНИЕ БАЗЫ</h4>
                    <p>Мы следим за изменениями адресов, поэтому наши данные всегда актуальны</p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="benefitsWrap">
            <div class="westSide">
                <div class="desc trig3">
                    <h4>СТАБИЛЬНОСТЬ СЕРВЕРОВ</h4>
                    <p>Сервера с базой располагаются в облаке Digital Ocean, с настроенной системой распределения
                        нагрузки. </p>
                </div>
            </div>
            <div class="eastSide">
                <div class="desc trig4">
                    <h4>СКОРОСТЬ РАБОТЫ</h4>
                    <p>Мы провели не один час оптимизируя базу данных, запросы и кеширование. В результате
                        добились отличных результатов по части скорости работы сервиса.</p>
                </div>
            </div>
            <div class="clear"></div>
            <div class="middleSide">
                <div class="desc trig5">
                    <h4>OPEN SOURCE</h4>
                    <p>Все исходные коды сервиса доступны в открытом виде.
                        Благодаря этому наш проект не стоит на месте, Вы можете принять участие в разработке проекта</p>
                </div>
            </div>
        </div>
    </div>
    <div class="faq">
        <div class="cBlock">
            <h2>вопросы и ответы</h2>
            <div class="question">
                <p><span>Сколько стоит ваш сервис?</span></p>
                <p>Сервис КЛАДР в облаке бесплатный, но есть ограничение на количество запросов. <br>Подробнее <a href="/prices">в разделе «Условия»</a>.</p>
            </div>
            <div class="question">
                <p><span>Есть ли коммерческая поддержка?</span></p>
                <p>Да, специально для бизнеса есть платная подписка, оформив которую вы снимите все ограничения и получаете гарантированную работу серверов. Подробнее можно узнать на странице <a href="/business">описания условия</a></p>
            </div>
            <div class="question">
                <p><span>Можно ли поучаствовать в разрабоке сервиса?</span></p>
                <p>Мы всегда рады конструктивному диалогу, предложениям и идеям, поэтому если у Вас появится желание с нами связаться, вот наши <a href="/contacts/">контактные данные</a></p>
            </div>
            <a class="allFaq" href="/prices#faq">Все вопросы и ответы</a>
        </div>
    </div>
    <div class="serviceRates cBlock">
        <h2>тарифы сервиса</h2>
        <div class="ratesBlock">
            <div class="westSide">
                <h2>Бесплатно</h2>
                <div class="img">
                    <img src="img/freePrice.png" alt=""/>
                </div>
                <div class="desc">
                    <p>Сервис является абсолютно бесплатным с открытыми исходными кодами для некоммерческого
                        использования.</p>
                </div>
                <a href="/integration" class="button">Подключить</a>
            </div>
            <div class="middleSide">
                <div class="rel">
                    <div class="label"></div>
                    <h2>Бизнес</h2>
                    <div class="img">
                        <img src="img/specialPrice.png" alt=""/>
                    </div>
                    <div class="desc">
                        <p>Бизнес поддержка. <br>Отдельные сервера и гарантированная работа сервиса. Консультирование по скайпу.</p>
                    </div>
                    <a href="/business" class="button">Подключить</a>
                    <div class="specialShadow"></div>
                </div>
            </div>
            <div class="eastSide">
                <h2>Коробка</h2>
                <div class="img">
                    <img src="img/boxPrice.png" alt=""/>
                </div>
                <div class="desc">
                    <p>Установка сервиса на ваши сервера. Поддержка и обновления.</p>
                </div>
                <a href="/business#box" class="button">Подключить</a>
            </div>
            <div class="ratesShadow"></div>
        </div>
    </div>
