<div class="footer">
    <div class="cBlock">
	<div class="footerWrap">
	    <div class="westSide">
		<p><span>КЛАДР в облаке</span></p>
		<p>Сделано в <a href="http://primepix.ru">PrimePix</a></p>
	    </div>
	    <div class="middleSide">
		<p>Будьте на связи</p>
		<div class="socialBox">
		    <a href="http://twitter.com/kladrapi"><img src="/img/twitter.png" alt=""/></a>
		    <a href="https://trello.com/b/NlSSs2UV/-"><img src="/img/trello.png" alt=""/></a>
		    <a href="https://github.com/garakh/kladrapi"><img src="/img/gitHub.png" alt=""/></a>
		</div>
		<div class="ask">
		    <a  href="/contacts">Задать вопрос</a>

		</div>
	    </div>
	    <div class="clear"></div>
	    <div class="footerNav">
		<ul>
		    <li><a href="/">О сервисе</a></li>
		    <li><a href="/prices">Условия</a></li>
		    <li><a href="/business">Для бизнеса</a></li>
		    <li><a href="/examples">Примеры</a></li>
		    <li><a href="/integration">Документация</a></li>
		    <li><a href="/contacts">Контактная информация</a></li>
		</ul>
	    </div>
	</div>
    </div>
</div>

