
<div class="nav">
    <ul class="cBlock">
	<li <?php if ($page == 'index'): ?>class="active"<?php endif ?>><a href="/">Как это работает</a></li>
	<li <?php if ($page == 'prices'): ?>class="active"<?php endif ?>><a href="/prices">Условия</a></li>
	<li <?php if ($page == 'business'): ?>class="active"<?php endif ?>><a href="/business">Для бизнеса</a></li>
	<li <?php if ($page == 'examples'): ?>class="active"<?php endif ?>><a href="/examples">Примеры</a></li>
	<li <?php if ($page == 'integration'): ?>class="active"<?php endif ?>><a href="/integration/">Документация</a></li>
	
    </ul>
</div>
<?php if (!isset($hideSmallHeader)): ?>
    <div class="headerInt">
        <div class="cBlock">
    	<div class="westSide">
    	    <div class="img">
    		<img src="/img/smallLogo.png" alt=""/>
    	    </div>
    	    <h3>КЛАДР в облаке</h3>
    	</div>
    	<div class="middleSide">
    	    <p>Простой и удобный сервиc для работы с базой адресов</p>
    	</div>
        </div>
    </div>
    <?php
endif?>