<div class="header">
    <div class="inheader">
        <div class="authline">
            <div class="correctwidth">
                <?= $this->elements->getAuth() ?></div>
            <noindex><a href="https://twitter.com/kladrapi" target="_blank" class="twitter btn-enter">Мы в Твиттере</a></noindex>
        </div>
        <div class="controlline">
            <div class="correctwidth">
                <div class="logo"><a href="/"></a></div>
                <div class="menu"><?= $this->elements->getTopMenu() ?></div>
                <div class="social">
                    <noindex><a href="https://trello.com/b/NlSSs2UV/-" class="trello" >&#0076;</a></noindex>
                    <noindex><a href="https://github.com/garakh/kladrapi" class="github">&#0082;</a></noindex>
                    <noindex><a href="https://twitter.com/kladrapi" target="_blank" class="twitter">&#229;</a></noindex>
                </div>
            </div>
        </div>
    </div>
</div>