<?php use \Phalcon\Tag; ?>

<div id="login-popap" class="propose register" style="display: none;">
    <div class="reg login">
        <?php echo Tag::form(array("login", "method" => "post")); ?>
        <p>Вход</p>
        <?php echo Tag::textField(array("email", "id" => "inputEmail", "placeholder" => "ваш e-mail", "data-email" => "y")) ?>
        <?php echo Tag::passwordField(array("password", "id" => "inputPassword", "placeholder" => "пароль")) ?>
        <a href="/recovery/">Не помню пароль</a>
        <?php echo Tag::submitButton(array('Войти', "class" => "btn")) ?>
        <?php echo Tag::endForm(); ?>
    </div>
</div>