<?php use \Phalcon\Tag; ?>

<div id="register-popap" class="propose register" style="display: none;">
    <div class="reg">
        <?= Tag::form(array("register", "method" => "post")); ?>
        <p>Регистрация</p>
        <?= Tag::textField(array("email", "id" => "inputEmail", "placeholder" => "ваш e-mail", "data-email" => "y")) ?>
        <div class="checkbox">
            <?= Tag::checkField(array("accept", "id" => "accept_modal", "value" => "y")) ?>
            <label for="accept_modal">Согласен с <a href="/prices/#conditions" target="_blank">условиями использования сервиса</a></label> 
        </div>
        <?= Tag::submitButton(array('Регистрация', "class" => "btn")) ?>
        <?= Tag::endForm(); ?>
    </div>
</div>