<div class="content">
    <div class="cBlock">
	<div class="contentMain">
	    <h1>Форум</h1>






	    <iframe id="forum_embed"
		    src="javascript:void(0)"
		    scrolling="no"
		    frameborder="0"
		    width="900"
		    height="1500">
	    </iframe>
	    <script type="text/javascript">
		document.getElementById('forum_embed').src =
		    'https://groups.google.com/forum/embed/?place=forum/kladrapi'
		    + '&showsearch=true&showpopout=true&showtabs=false'
		    + '&parenturl=' + encodeURIComponent('http://kaldr-api.ru/');
	    </script>

	</div>      
    </div>
</div>