<div class="otherheader">
    <h1>Форум</h1>
</div>



<div class="correctwidth">
    <div class="content">


        <iframe id="forum_embed"
                src="javascript:void(0)"
                scrolling="no"
                frameborder="0"
                width="900"
                height="700">
        </iframe>
        <script type="text/javascript">
            document.getElementById('forum_embed').src =
                    'https://groups.google.com/forum/embed/?place=forum/kladrapi'
                            + '&showsearch=true&showpopout=true&showtabs=false'
                            + '&parenturl=' + encodeURIComponent('http://kaldr-api.ru/');
        </script>

    </div>      
</div>