<div class="otherheader">
    <h1>Примеры</h1>
</div>

<link href="css/ui-lightness/jquery-ui-1.10.2.custom.css" rel="stylesheet">
<link href="css/examples.css" rel="stylesheet">
<link href="css/example1.css" rel="stylesheet">
<link href="css/example2.css" rel="stylesheet">
<link href="css/example3.css" rel="stylesheet">
<link href="css/example4.css" rel="stylesheet">

<script src="js/lib/jquery-1.9.1.min.js"></script>
<script src="js/lib/jquery-ui-1.10.2.custom.min.js"></script>
<script src="js/lib/jquery.primepix.kladr.min.js"></script>
<script src="js/examples.js"></script>
<script src="js/example1.js"></script>
<script src="js/example2.js"></script>
<script src="js/example3.js"></script>
<script src="js/example4.js"></script>

<script src="http://api-maps.yandex.ru/2.0.18/?load=package.standard&mode=release&lang=ru-RU" type="text/javascript"></script>

<div class="correctwidth">
    <div class="content">
        <p>Поиск улицы в г. Москва</p>        
        <div id="example1" class="tabs">
            <ul>
                <li><a href="#tabs-1-1">Просмотр</a></li>
                <li><a href="#tabs-1-2">HTML</a></li>
                <li><a href="#tabs-1-3">CSS</a></li>
                <li><a href="#tabs-1-4">JS</a></li>
            </ul>
            <div id="tabs-1-1">
                <div class ="address">
                    <h1>Поиск улицы в г. Москва</h1>
                    <div class="field">
                        <input name="street" type="text" value="">
                    </div>
                </div>
            </div>
            <div id="tabs-1-2">
                <div class="scme">
                    <a href="html/example1-source.html" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="kwrd">&lt;!</span><span class="html">DOCTYPE</span> <span class="attr">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   2:  </span><span class="kwrd">&lt;</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="kwrd">&lt;</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">&lt;</span><span class="html">meta</span> <span class="attr">http-equiv</span><span class="kwrd">="content-type"</span> <span class="attr">content</span><span class="kwrd">="text/html; charset=utf-8"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   5:  </span>        <span class="kwrd">&lt;</span><span class="html">title</span><span class="kwrd">&gt;</span>Пример 1<span class="kwrd">&lt;/</span><span class="html">title</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   6:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/ui-lightness/jquery-ui-1.10.2.custom.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre><span class="lnum">   8:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/example1.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   9:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  10:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-1.9.1.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  11:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-ui-1.10.2.custom.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  12:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../../jquery.primepix.kladr.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  13:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/example1.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  14:  </span>    <span class="kwrd">&lt;/</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  15:  </span>    <span class="kwrd">&lt;</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  16:  </span>        <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span> <span class="kwrd">="address"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  17:  </span>            <span class="kwrd">&lt;</span><span class="html">h1</span><span class="kwrd">&gt;</span>Поиск улицы в г. Москва<span class="kwrd">&lt;/</span><span class="html">h1</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  18:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="field"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  19:  </span>                <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="street"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">value</span><span class="kwrd">=""&gt;</span></pre>
                        <pre><span class="lnum">  20:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  21:  </span>        <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  22:  </span>    <span class="kwrd">&lt;/</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  23:  </span><span class="kwrd">&lt;/</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  24:  </span>&nbsp;</pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-1-3">
                <div class="scme">
                    <a href="css/example1.css" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="str">.address</span>{</pre>
                        <pre><span class="lnum">   2:  </span>    <span class="attr">width</span>: <span class="kwrd">295px</span>;</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="attr">margin</span>: <span class="kwrd">20px auto</span>;</pre>
                        <pre><span class="lnum">   4:  </span>    <span class="attr">padding</span>: <span class="kwrd">10px</span>;</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>    <span class="attr">border</span>: <span class="kwrd">1px solid rgb</span>(<span class="rem">104,&nbsp;104,&nbsp;104</span>);</pre>
                        <pre><span class="lnum">   6:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">5px</span>;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>    <span class="attr">font-size</span>: <span class="kwrd">0.8em</span>;</pre>
                        <pre><span class="lnum">   8:  </span>    <span class="attr">line-height</span>: <span class="kwrd">25px</span>;</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>}</pre>
                        <pre><span class="lnum">  10:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span><span class="str">.address h1</span>{</pre>
                        <pre><span class="lnum">  12:  </span>    <span class="attr">margin</span>: <span class="kwrd">0</span>;</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>    <span class="attr">padding</span>: <span class="kwrd">0</span>;</pre>
                        <pre><span class="lnum">  14:  </span>    <span class="attr">font-size</span>: <span class="kwrd">25px</span>;</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>    <span class="attr">padding-bottom</span>: <span class="kwrd">10px</span>;</pre>
                        <pre><span class="lnum">  16:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  17:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  18:  </span><span class="str">.field input</span>{</pre>
                        <pre class="alt"><span class="lnum">  19:  </span>    <span class="attr">width</span>: <span class="kwrd">290px</span>;</pre>
                        <pre><span class="lnum">  20:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  21:  </span>&nbsp;</pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-1-4">
                <div class="scme">
                    <a href="js/example1.js" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span>(<span class="kwrd">function</span>($){</pre>
                        <pre><span class="lnum">   2:  </span>    $(<span class="kwrd">function</span>() {</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>        $( <span class="str">'[name="street"]'</span> ).kladr({</pre>
                        <pre><span class="lnum">   4:  </span>            token: <span class="str">'51dfe5d42fb2b43e3300006e'</span>,</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>            key: <span class="str">'86a2c2a06f1b2451a87d05512cc2c3edfdf41969'</span>,</pre>
                        <pre><span class="lnum">   6:  </span>            type: $.ui.kladrObjectType.STREET,</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>            parentType: $.ui.kladrObjectType.CITY,</pre>
                        <pre><span class="lnum">   8:  </span>            parentId: <span class="str">'7700000000000'</span></pre>
                        <pre class="alt"><span class="lnum">   9:  </span>        });</pre>
                        <pre><span class="lnum">  10:  </span>    });</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>})(jQuery); </pre>
                    </ol>
                </div>
            </div>
        </div>
        
        <p>Поиск улиц в определённых городах</p> 
        <div id="example2" class="tabs">
            <ul>
                <li><a href="#tabs-2-1">Просмотр</a></li>
                <li><a href="#tabs-2-2">HTML</a></li>
                <li><a href="#tabs-2-3">CSS</a></li>
                <li><a href="#tabs-2-4">JS</a></li>
            </ul>
            <div id="tabs-2-1">
                <div class ="address">
                    <div class="field">
                        <label>Населённый пункт:</label>
                        <select name="city">
                            <option value="7700000000000" selected="selected">Москва</option>
                            <option value="7800000000000">Санкт-Петербург</option>
                        </select>
                    </div>
                    <div class="field">
                        <label>Улица:</label>
                        <input name="street" type="text" value="">
                    </div>
                </div>
            </div>
            <div id="tabs-2-2">
                <div class="scme">
                    <a href="html/example2-source.html" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="kwrd">&lt;!</span><span class="html">DOCTYPE</span> <span class="attr">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   2:  </span><span class="kwrd">&lt;</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="kwrd">&lt;</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">&lt;</span><span class="html">meta</span> <span class="attr">http-equiv</span><span class="kwrd">="content-type"</span> <span class="attr">content</span><span class="kwrd">="text/html; charset=utf-8"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   5:  </span>        <span class="kwrd">&lt;</span><span class="html">title</span><span class="kwrd">&gt;</span>Пример 2<span class="kwrd">&lt;/</span><span class="html">title</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   6:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/ui-lightness/jquery-ui-1.10.2.custom.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre><span class="lnum">   8:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/example2.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   9:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  10:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-1.9.1.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  11:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-ui-1.10.2.custom.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  12:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../../jquery.primepix.kladr.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  13:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/example2.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  14:  </span>    <span class="kwrd">&lt;/</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  15:  </span>    <span class="kwrd">&lt;</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  16:  </span>        <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span> <span class="kwrd">="address"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  17:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="field"&gt;</span></pre>
                        <pre><span class="lnum">  18:  </span>                <span class="kwrd">&lt;</span><span class="html">label</span><span class="kwrd">&gt;</span>Населённый пункт:<span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  19:  </span>                <span class="kwrd">&lt;</span><span class="html">select</span> <span class="attr">name</span><span class="kwrd">="city"&gt;</span></pre>
                        <pre><span class="lnum">  20:  </span>                    <span class="kwrd">&lt;</span><span class="html">option</span> <span class="attr">value</span><span class="kwrd">="7700000000000"</span> <span class="attr">selected</span><span class="kwrd">="selected"&gt;</span>Москва<span class="kwrd">&lt;/</span><span class="html">option</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  21:  </span>                    <span class="kwrd">&lt;</span><span class="html">option</span> <span class="attr">value</span><span class="kwrd">="7800000000000"&gt;</span>Санкт-Петербург<span class="kwrd">&lt;/</span><span class="html">option</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  22:  </span>                <span class="kwrd">&lt;/</span><span class="html">select</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  23:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  24:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="field"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  25:  </span>                <span class="kwrd">&lt;</span><span class="html">label</span><span class="kwrd">&gt;</span>Улица:<span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  26:  </span>                <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="street"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">value</span><span class="kwrd">=""&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  27:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  28:  </span>        <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  29:  </span>    <span class="kwrd">&lt;/</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  30:  </span><span class="kwrd">&lt;/</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  31:  </span>&nbsp;</pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-2-3">
                <div class="scme">
                    <a href="css/example2.css" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="str">.address</span>{</pre>
                        <pre><span class="lnum">   2:  </span>    <span class="attr">width</span>: <span class="kwrd">340px</span>;</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="attr">margin</span>: <span class="kwrd">20px auto</span>;</pre>
                        <pre><span class="lnum">   4:  </span>    <span class="attr">padding</span>: <span class="kwrd">10px</span>;</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>    <span class="attr">border</span>: <span class="kwrd">1px solid rgb</span>(<span class="rem">104,&nbsp;104,&nbsp;104</span>);</pre>
                        <pre><span class="lnum">   6:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">5px</span>;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>    <span class="attr">font-size</span>: <span class="kwrd">0.8em</span>;</pre>
                        <pre><span class="lnum">   8:  </span>    <span class="attr">line-height</span>: <span class="kwrd">25px</span>;</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>}</pre>
                        <pre><span class="lnum">  10:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span><span class="str">.field label</span>{</pre>
                        <pre><span class="lnum">  12:  </span>    <span class="attr">display</span>: <span class="kwrd">block</span>;</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre><span class="lnum">  14:  </span>    <span class="attr">width</span>: <span class="kwrd">135px</span>;</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>}</pre>
                        <pre><span class="lnum">  16:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  17:  </span><span class="str">.field input</span>,</pre>
                        <pre><span class="lnum">  18:  </span><span class="str">.field select</span>{</pre>
                        <pre class="alt"><span class="lnum">  19:  </span>    <span class="attr">width</span>: <span class="kwrd">200px</span>;</pre>
                        <pre><span class="lnum">  20:  </span>} </pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-2-4">
                <div class="scme">
                    <a href="js/example2.js" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span>(<span class="kwrd">function</span>($){</pre>
                        <pre><span class="lnum">   2:  </span>    $(<span class="kwrd">function</span>() {</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>        <span class="kwrd">var</span> city = $( <span class="str">'[name="city"]'</span> );</pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">var</span> street = $( <span class="str">'[name="street"]'</span> );</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>&nbsp;</pre>
                        <pre><span class="lnum">   6:  </span>        street.kladr({</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>            token: <span class="str">'51dfe5d42fb2b43e3300006e'</span>,</pre>
                        <pre><span class="lnum">   8:  </span>            key: <span class="str">'86a2c2a06f1b2451a87d05512cc2c3edfdf41969'</span>,</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>            type: $.ui.kladrObjectType.STREET,</pre>
                        <pre><span class="lnum">  10:  </span>            parentType: $.ui.kladrObjectType.CITY,</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>            parentId: city.val()</pre>
                        <pre><span class="lnum">  12:  </span>        });</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  14:  </span>        city.change(<span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>            street.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: city.val() } );</pre>
                        <pre><span class="lnum">  16:  </span>        });</pre>
                        <pre class="alt"><span class="lnum">  17:  </span>    });</pre>
                        <pre><span class="lnum">  18:  </span>})(jQuery); </pre>
                    </ol>
                </div>
            </div>
        </div>
        
        <p>Автодополнение городов и улиц</p>
        <div id="example3" class="tabs">
            <ul>
                <li><a href="#tabs-3-1">Просмотр</a></li>
                <li><a href="#tabs-3-2">HTML</a></li>
                <li><a href="#tabs-3-3">CSS</a></li>
                <li><a href="#tabs-3-4">JS</a></li>
            </ul>
            <div id="tabs-3-1">
                <div class ="address">
                    <div class="field">
                        <label>Населённый пункт:</label>
                        <input name="location" type="text" value="">
                    </div>
                    <div class="field">
                        <label>Улица:</label>
                        <input name="street" type="text" value="">
                    </div>
                </div>
            </div>
            <div id="tabs-3-2">
                <div class="scme">
                    <a href="html/example3-source.html" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="kwrd">&lt;!</span><span class="html">DOCTYPE</span> <span class="attr">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   2:  </span><span class="kwrd">&lt;</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="kwrd">&lt;</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">&lt;</span><span class="html">meta</span> <span class="attr">http-equiv</span><span class="kwrd">="content-type"</span> <span class="attr">content</span><span class="kwrd">="text/html; charset=utf-8"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   5:  </span>        <span class="kwrd">&lt;</span><span class="html">title</span><span class="kwrd">&gt;</span>Пример 3<span class="kwrd">&lt;/</span><span class="html">title</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   6:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/ui-lightness/jquery-ui-1.10.2.custom.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre><span class="lnum">   8:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/example3.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   9:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  10:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-1.9.1.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  11:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-ui-1.10.2.custom.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  12:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../../jquery.primepix.kladr.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  13:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/example3.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  14:  </span>    <span class="kwrd">&lt;/</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  15:  </span>    <span class="kwrd">&lt;</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  16:  </span>        <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span> <span class="kwrd">="address"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  17:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="field"&gt;</span></pre>
                        <pre><span class="lnum">  18:  </span>                <span class="kwrd">&lt;</span><span class="html">label</span><span class="kwrd">&gt;</span>Населённый пункт:<span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  19:  </span>                <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="location"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">value</span><span class="kwrd">=""&gt;</span></pre>
                        <pre><span class="lnum">  20:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  21:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="field"&gt;</span></pre>
                        <pre><span class="lnum">  22:  </span>                <span class="kwrd">&lt;</span><span class="html">label</span><span class="kwrd">&gt;</span>Улица:<span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  23:  </span>                <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="street"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">value</span><span class="kwrd">=""&gt;</span></pre>
                        <pre><span class="lnum">  24:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  25:  </span>        <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  26:  </span>    <span class="kwrd">&lt;/</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  27:  </span><span class="kwrd">&lt;/</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  28:  </span>&nbsp;</pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-3-3">
                <div class="scme">
                    <a href="css/example3.css" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="str">.address</span>{</pre>
                        <pre><span class="lnum">   2:  </span>    <span class="attr">width</span>: <span class="kwrd">340px</span>;</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="attr">margin</span>: <span class="kwrd">20px auto</span>;</pre>
                        <pre><span class="lnum">   4:  </span>    <span class="attr">padding</span>: <span class="kwrd">10px</span>;</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>    <span class="attr">border</span>: <span class="kwrd">1px solid rgb</span>(<span class="rem">104,&nbsp;104,&nbsp;104</span>);</pre>
                        <pre><span class="lnum">   6:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">5px</span>;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>    <span class="attr">font-size</span>: <span class="kwrd">0.8em</span>;</pre>
                        <pre><span class="lnum">   8:  </span>    <span class="attr">line-height</span>: <span class="kwrd">25px</span>;</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>}</pre>
                        <pre><span class="lnum">  10:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span><span class="str">.field label</span>{</pre>
                        <pre><span class="lnum">  12:  </span>    <span class="attr">display</span>: <span class="kwrd">block</span>;</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre><span class="lnum">  14:  </span>    <span class="attr">width</span>: <span class="kwrd">135px</span>;</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>}</pre>
                        <pre><span class="lnum">  16:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  17:  </span><span class="str">.field input</span>{</pre>
                        <pre><span class="lnum">  18:  </span>    <span class="attr">width</span>: <span class="kwrd">200px</span>;</pre>
                        <pre class="alt"><span class="lnum">  19:  </span>} </pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-3-4">
                <div class="scme">
                    <a href="js/example3.js" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span>(<span class="kwrd">function</span>($){</pre>
                        <pre><span class="lnum">   2:  </span>    $(<span class="kwrd">function</span>() {</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>        $( <span class="str">'[name="location"]'</span> ).kladr({</pre>
                        <pre><span class="lnum">   4:  </span>            token: <span class="str">'51dfe5d42fb2b43e3300006e'</span>,</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>            key: <span class="str">'86a2c2a06f1b2451a87d05512cc2c3edfdf41969'</span>,</pre>
                        <pre><span class="lnum">   6:  </span>            type: $.ui.kladrObjectType.CITY,</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>            select: <span class="kwrd">function</span>( <span class="kwrd">event</span>, ui ) {</pre>
                        <pre><span class="lnum">   8:  </span>                $( <span class="str">'[name="street"]'</span> ).kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: ui.item.obj.id } );</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>            }</pre>
                        <pre><span class="lnum">  10:  </span>        });</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  12:  </span>        $( <span class="str">'[name="street"]'</span> ).kladr({</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>            token: <span class="str">'51dfe5d42fb2b43e3300006e'</span>,</pre>
                        <pre><span class="lnum">  14:  </span>            key: <span class="str">'86a2c2a06f1b2451a87d05512cc2c3edfdf41969'</span>,</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>            type: $.ui.kladrObjectType.STREET</pre>
                        <pre><span class="lnum">  16:  </span>        });</pre>
                        <pre class="alt"><span class="lnum">  17:  </span>    });</pre>
                        <pre><span class="lnum">  18:  </span>})(jQuery); </pre>
                    </ol>
                </div>
            </div>
        </div>
        
        <p>Расширенный пример</p>
        <div id="example4" class="tabs">
            <ul>
                <li><a href="#tabs-4-1">Просмотр</a></li>
                <li><a href="#tabs-4-2">HTML</a></li>
                <li><a href="#tabs-4-3">CSS</a></li>
                <li><a href="#tabs-4-4">JS</a></li>
            </ul>
            <div id="tabs-4-1">
                <div class="add-panel">
                    <div class="wrp">
                        <form class="add-panel__request regular__ctrls">
                            <div class="ffield">
                                <label class="ffield__lbl">
                                    Город
                                </label>
                                <input name="city" type="text" class="long">
                                <img src="images/spinner.gif" class="spinner">
                            </div>
                            <div class="ffield">
                                <label class="ffield__lbl">
                                    Улица
                                </label>
                                <input name="street" type="text" class="long">
                                <img src="images/spinner.gif" class="spinner">
                            </div>
                            <div class="ffield">
                                <label class="ffield__lbl">
                                    Номер дома
                                </label>
                                <input name="building" type="text" class="small">
                                <img src="images/spinner.gif" class="spinner spinner2">

                                <label class="ffield__lbl2">
                                    Корпус/строение
                                </label>
                                <input name="building-add" type="text" class="small">
                            </div>
                            <div class="ffield">
                                <label class="ffield__lbl ltooltip"></label>
                                <div id="map" class="add-panel__map"></div>
                            </div>
                        </form>
                        <div class="addition">
                            <div class="block">
                                <p class="title">Выбранный объект</p>
                                <ul>
                                    <li id="id" style="display: none;"><span class="name">Код:</span> <span class="value">2900000100000</span></li>
                                    <li id="zip" style="display: none;"><span class="name">Почтовый индекс:</span> <span class="value"></span></li>
                                    <li id="name" style="display: none;"><span class="name">Название:</span> <span class="value">Архангельск</span></li>                        
                                    <li id="type" style="display: none;"><span class="name">Тип:</span> <span class="value"></span></li>
                                    <li id="type_short" style="display: none;"><span class="name">Тип коротко:</span> <span class="value"></span></li>
                                </ul>
                            </div>
                            <div class="block">
                                <p class="title">Текстовое представление адреса</p>
                                <p id="address" class="value"></p>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="tabs-4-2">
                <div class="scme">
                    <a href="html/example4-source.html" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span><span class="kwrd">&lt;!</span><span class="html">DOCTYPE</span> <span class="attr">html</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   2:  </span><span class="kwrd">&lt;</span><span class="html">html</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="kwrd">&lt;</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">&lt;</span><span class="html">meta</span> <span class="attr">http-equiv</span><span class="kwrd">="content-type"</span> <span class="attr">content</span><span class="kwrd">="text/html; charset=utf-8"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   5:  </span>        <span class="kwrd">&lt;</span><span class="html">title</span><span class="kwrd">&gt;</span>Расширенный пример<span class="kwrd">&lt;/</span><span class="html">title</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">   6:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/ui-lightness/jquery-ui-1.10.2.custom.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"&gt;</span></pre>
                        <pre><span class="lnum">   8:  </span>        <span class="kwrd">&lt;</span><span class="html">link</span> <span class="attr">href</span><span class="kwrd">="../css/example4.css"</span> <span class="attr">rel</span><span class="kwrd">="stylesheet"</span> <span class="attr">type</span><span class="kwrd">="text/css"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">   9:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  10:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-1.9.1.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  12:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/lib/jquery-ui-1.10.2.custom.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  13:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../../jquery.primepix.kladr.min.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  14:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"../js/example4.js"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  15:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  16:  </span>        <span class="kwrd">&lt;</span><span class="html">script</span> src=<font color="#A31515">"http://api-maps.yandex.ru/2.0.18/?load=package.standard&amp;mode=release&amp;lang=ru-RU"</font> type=<font color="#A31515">"text/javascript"</font>&gt;<span class="kwrd">&lt;/</span><span class="html">script</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  17:  </span>    <span class="kwrd">&lt;/</span><span class="html">head</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  18:  </span>    <span class="kwrd">&lt;</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  19:  </span>        <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="add-panel"&gt;</span></pre>
                        <pre><span class="lnum">  20:  </span>            <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="wrp"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  21:  </span>                <span class="kwrd">&lt;</span><span class="html">form</span> <span class="attr">class</span><span class="kwrd">="add-panel__request regular__ctrls"&gt;</span></pre>
                        <pre><span class="lnum">  22:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="ffield"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  23:  </span>                        <span class="kwrd">&lt;</span><span class="html">label</span> <span class="attr">class</span><span class="kwrd">="ffield__lbl"&gt;</span></pre>
                        <pre><span class="lnum">  24:  </span>                            Город</pre>
                        <pre class="alt"><span class="lnum">  25:  </span>                        <span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  26:  </span>                        <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="city"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">class</span><span class="kwrd">="long"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  27:  </span>                        <span class="kwrd">&lt;</span><span class="html">img</span> <span class="attr">src</span><span class="kwrd">="../images/spinner.gif"</span> <span class="attr">class</span><span class="kwrd">="spinner"&gt;</span></pre>
                        <pre><span class="lnum">  28:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  29:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="ffield"&gt;</span></pre>
                        <pre><span class="lnum">  30:  </span>                        <span class="kwrd">&lt;</span><span class="html">label</span> <span class="attr">class</span><span class="kwrd">="ffield__lbl"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  31:  </span>                            Улица</pre>
                        <pre><span class="lnum">  32:  </span>                        <span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  33:  </span>                        <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="street"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">class</span><span class="kwrd">="long"&gt;</span></pre>
                        <pre><span class="lnum">  34:  </span>                        <span class="kwrd">&lt;</span><span class="html">img</span> <span class="attr">src</span><span class="kwrd">="../images/spinner.gif"</span> <span class="attr">class</span><span class="kwrd">="spinner"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  35:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  36:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="ffield"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  37:  </span>                        <span class="kwrd">&lt;</span><span class="html">label</span> <span class="attr">class</span><span class="kwrd">="ffield__lbl"&gt;</span></pre>
                        <pre><span class="lnum">  38:  </span>                            Номер дома</pre>
                        <pre class="alt"><span class="lnum">  39:  </span>                        <span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  40:  </span>                        <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="building"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">class</span><span class="kwrd">="small"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  41:  </span>                        <span class="kwrd">&lt;</span><span class="html">img</span> <span class="attr">src</span><span class="kwrd">="../images/spinner.gif"</span> <span class="attr">class</span><span class="kwrd">="spinner spinner2"&gt;</span></pre>
                        <pre><span class="lnum">  42:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  43:  </span>                        <span class="kwrd">&lt;</span><span class="html">label</span> <span class="attr">class</span><span class="kwrd">="ffield__lbl2"&gt;</span></pre>
                        <pre><span class="lnum">  44:  </span>                            Корпус/строение</pre>
                        <pre class="alt"><span class="lnum">  45:  </span>                        <span class="kwrd">&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  46:  </span>                        <span class="kwrd">&lt;</span><span class="html">input</span> <span class="attr">name</span><span class="kwrd">="building-add"</span> <span class="attr">type</span><span class="kwrd">="text"</span> <span class="attr">class</span><span class="kwrd">="small"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  47:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  48:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="ffield"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  49:  </span>                        <span class="kwrd">&lt;</span><span class="html">label</span> <span class="attr">class</span><span class="kwrd">="ffield__lbl ltooltip"&gt;&lt;/</span><span class="html">label</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  50:  </span>                        <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">id</span><span class="kwrd">="map"</span> <span class="attr">class</span><span class="kwrd">="add-panel__map"&gt;&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  51:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  52:  </span>                <span class="kwrd">&lt;/</span><span class="html">form</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  53:  </span>                <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="addition"&gt;</span></pre>
                        <pre><span class="lnum">  54:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="block"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  55:  </span>                        <span class="kwrd">&lt;</span><span class="html">p</span> <span class="attr">class</span><span class="kwrd">="title"&gt;</span>Выбранный объект<span class="kwrd">&lt;/</span><span class="html">p</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  56:  </span>                        <span class="kwrd">&lt;</span><span class="html">ul</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  57:  </span>                            <span class="kwrd">&lt;</span><span class="html">li</span> <span class="attr">id</span><span class="kwrd">="id"</span> <span class="attr">style</span><span class="kwrd">="display: none;"&gt;&lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="name"&gt;</span>Код:<span class="kwrd">&lt;/</span><span class="html">span</span><span class="kwrd">&gt; &lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">span</span><span class="kwrd">&gt;&lt;/</span><span class="html">li</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  58:  </span>                            <span class="kwrd">&lt;</span><span class="html">li</span> <span class="attr">id</span><span class="kwrd">="zip"</span> <span class="attr">style</span><span class="kwrd">="display: none;"&gt;&lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="name"&gt;</span>Почтовый индекс:<span class="kwrd">&lt;/</span><span class="html">span</span><span class="kwrd">&gt; &lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">span</span><span class="kwrd">&gt;&lt;/</span><span class="html">li</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  59:  </span>                            <span class="kwrd">&lt;</span><span class="html">li</span> <span class="attr">id</span><span class="kwrd">="name"</span> <span class="attr">style</span><span class="kwrd">="display: none;"&gt;&lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="name"&gt;</span>Название:<span class="kwrd">&lt;/</span><span class="html">span</span><span class="kwrd">&gt; &lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">span</span><span class="kwrd">&gt;&lt;/</span><span class="html">li</span><span class="kwrd">&gt;</span>                        </pre>
                        <pre><span class="lnum">  60:  </span>                            <span class="kwrd">&lt;</span><span class="html">li</span> <span class="attr">id</span><span class="kwrd">="type"</span> <span class="attr">style</span><span class="kwrd">="display: none;"&gt;&lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="name"&gt;</span>Тип:<span class="kwrd">&lt;/</span><span class="html">span</span><span class="kwrd">&gt; &lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">span</span><span class="kwrd">&gt;&lt;/</span><span class="html">li</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  61:  </span>                            <span class="kwrd">&lt;</span><span class="html">li</span> <span class="attr">id</span><span class="kwrd">="type_short"</span> <span class="attr">style</span><span class="kwrd">="display: none;"&gt;&lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="name"&gt;</span>Тип коротко:<span class="kwrd">&lt;/</span><span class="html">span</span><span class="kwrd">&gt; &lt;</span><span class="html">span</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">span</span><span class="kwrd">&gt;&lt;/</span><span class="html">li</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  62:  </span>                        <span class="kwrd">&lt;/</span><span class="html">ul</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  63:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  64:  </span>                    <span class="kwrd">&lt;</span><span class="html">div</span> <span class="attr">class</span><span class="kwrd">="block"&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  65:  </span>                        <span class="kwrd">&lt;</span><span class="html">p</span> <span class="attr">class</span><span class="kwrd">="title"&gt;</span>Текстовое представление адреса<span class="kwrd">&lt;/</span><span class="html">p</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  66:  </span>                        <span class="kwrd">&lt;</span><span class="html">p</span> <span class="attr">id</span><span class="kwrd">="address"</span> <span class="attr">class</span><span class="kwrd">="value"&gt;&lt;/</span><span class="html">p</span><span class="kwrd">&gt;</span>                    </pre>
                        <pre class="alt"><span class="lnum">  67:  </span>                    <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  68:  </span>                <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  69:  </span>            <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  70:  </span>        <span class="kwrd">&lt;/</span><span class="html">div</span><span class="kwrd">&gt;</span></pre>
                        <pre class="alt"><span class="lnum">  71:  </span>    <span class="kwrd">&lt;/</span><span class="html">body</span><span class="kwrd">&gt;</span></pre>
                        <pre><span class="lnum">  72:  </span><span class="kwrd">&lt;/</span><span class="html">html</span><span class="kwrd">&gt;</span> </pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-4-3">
                <div class="scme">
                    <a href="css/example4.css" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span>﻿<span class="str">.add-panel</span> {</pre>
                        <pre><span class="lnum">   2:  </span>    <span class="attr">position</span>: <span class="kwrd">relative</span>;</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>    <span class="attr">z-index</span>: <span class="kwrd">100</span>;</pre>
                        <pre><span class="lnum">   4:  </span>    <span class="attr">margin</span>: <span class="kwrd">20px</span>;</pre>
                        <pre class="alt"><span class="lnum">   5:  </span>}</pre>
                        <pre><span class="lnum">   6:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">   7:  </span><span class="str">.add-panel .wrp</span> {</pre>
                        <pre><span class="lnum">   8:  </span>    <span class="attr">width</span>: <span class="kwrd">680px</span>;</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>    <span class="attr">margin</span>: <span class="kwrd">0 auto</span>;</pre>
                        <pre><span class="lnum">  10:  </span>    <span class="attr">position</span>: <span class="kwrd">relative</span>;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>}</pre>
                        <pre><span class="lnum">  12:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  13:  </span><span class="str">.add-panel__map</span> {</pre>
                        <pre><span class="lnum">  14:  </span>    <span class="attr">width</span>: <span class="kwrd">472px</span>;</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>    <span class="attr">height</span>: <span class="kwrd">147px</span>;</pre>
                        <pre><span class="lnum">  16:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre class="alt"><span class="lnum">  17:  </span>    <span class="attr">padding</span>: <span class="kwrd">10px</span>;</pre>
                        <pre><span class="lnum">  18:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">3px</span>;</pre>
                        <pre class="alt"><span class="lnum">  19:  </span>    <span class="attr">background</span>: <span class="kwrd">#F2F2F2</span>;</pre>
                        <pre><span class="lnum">  20:  </span>    -moz-box-shadow: <span class="kwrd">0px 1px 0px rgb</span>(<span class="rem">255,&nbsp;255,&nbsp;255</span>), <span class="kwrd">inset 0px 1px 3px</span> rgba(<span class="rem">0,&nbsp;0,&nbsp;0,&nbsp;0.25</span>);</pre>
                        <pre class="alt"><span class="lnum">  21:  </span>    -webkit-box-shadow: <span class="kwrd">0px 1px 0px rgb</span>(<span class="rem">255,&nbsp;255,&nbsp;255</span>), <span class="kwrd">inset 0px 1px 3px</span> rgba(<span class="rem">0,&nbsp;0,&nbsp;0,&nbsp;0.25</span>);</pre>
                        <pre><span class="lnum">  22:  </span>    box-shadow: <span class="kwrd">0px 1px 0px rgb</span>(<span class="rem">255,&nbsp;255,&nbsp;255</span>), <span class="kwrd">inset 0px 1px 3px</span> rgba(<span class="rem">0,&nbsp;0,&nbsp;0,&nbsp;0.25</span>);</pre>
                        <pre class="alt"><span class="lnum">  23:  </span>}</pre>
                        <pre><span class="lnum">  24:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  25:  </span><span class="str">#map</span> {</pre>
                        <pre><span class="lnum">  26:  </span>    <span class="attr">background</span>: <span class="kwrd">#F2F2F2</span>;</pre>
                        <pre class="alt"><span class="lnum">  27:  </span>    <span class="attr">background</span>-<span class="attr">size</span>: <span class="kwrd">473px 147px</span>;</pre>
                        <pre><span class="lnum">  28:  </span>    <span class="attr">cursor</span>: <span class="kwrd">move</span>;</pre>
                        <pre class="alt"><span class="lnum">  29:  </span>}</pre>
                        <pre><span class="lnum">  30:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  31:  </span><span class="str">.add-panel__request-ui input</span>[type=<span class="kwrd">"text"</span>],</pre>
                        <pre><span class="lnum">  32:  </span>{</pre>
                        <pre class="alt"><span class="lnum">  33:  </span>    <span class="attr">width</span>: <span class="kwrd">240px</span>;</pre>
                        <pre><span class="lnum">  34:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  35:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  36:  </span><span class="str">label</span> {</pre>
                        <pre class="alt"><span class="lnum">  37:  </span>    <span class="attr">font-size</span>: <span class="kwrd">100%</span>;</pre>
                        <pre><span class="lnum">  38:  </span>    <span class="attr">font</span>: <span class="kwrd">inherit</span>;</pre>
                        <pre class="alt"><span class="lnum">  39:  </span>    <span class="attr">font-weight</span>: <span class="kwrd">normal</span>;</pre>
                        <pre><span class="lnum">  40:  </span>    <span class="attr">font-style</span>: <span class="kwrd">normal</span>;</pre>
                        <pre class="alt"><span class="lnum">  41:  </span>    <span class="attr">vertical-align</span>: <span class="kwrd">baseline</span>;</pre>
                        <pre><span class="lnum">  42:  </span>    <span class="attr">font-family</span>:<span class="kwrd">&nbsp;Helvetica,&nbsp;Arial</span>;</pre>
                        <pre class="alt"><span class="lnum">  43:  </span>}</pre>
                        <pre><span class="lnum">  44:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  45:  </span><span class="str">.regular__ctrls .ffield</span> {</pre>
                        <pre><span class="lnum">  46:  </span>    <span class="attr">position</span>: <span class="kwrd">relative</span>;</pre>
                        <pre class="alt"><span class="lnum">  47:  </span>    <span class="attr">padding-top</span>: <span class="kwrd">2px</span>;</pre>
                        <pre><span class="lnum">  48:  </span>    <span class="attr">padding-bottom</span>: <span class="kwrd">11px</span>;</pre>
                        <pre class="alt"><span class="lnum">  49:  </span>    <span class="attr">overflow</span>: <span class="kwrd">hidden</span>;</pre>
                        <pre><span class="lnum">  50:  </span>    <span class="attr">width</span>: <span class="kwrd">100%</span>;</pre>
                        <pre class="alt"><span class="lnum">  51:  </span>}</pre>
                        <pre><span class="lnum">  52:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  53:  </span><span class="str">.regular__ctrls .spinner</span>{</pre>
                        <pre><span class="lnum">  54:  </span>    <span class="attr">position</span>: <span class="kwrd">absolute</span>;</pre>
                        <pre class="alt"><span class="lnum">  55:  </span>    <span class="attr">top</span>: <span class="kwrd">4px</span>;</pre>
                        <pre><span class="lnum">  56:  </span>    <span class="attr">right</span>: <span class="kwrd">21px</span>;</pre>
                        <pre class="alt"><span class="lnum">  57:  </span>    <span class="attr">display</span>: <span class="kwrd">none</span>;</pre>
                        <pre><span class="lnum">  58:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  59:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  60:  </span><span class="str">.regular__ctrls .spinner2</span> {</pre>
                        <pre class="alt"><span class="lnum">  61:  </span>    <span class="attr">left</span>: <span class="kwrd">300px</span>;</pre>
                        <pre><span class="lnum">  62:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  63:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  64:  </span><span class="str">.regular__ctrls .ffield__lbl</span> {</pre>
                        <pre class="alt"><span class="lnum">  65:  </span>    <span class="attr">display</span>:<span class="str"> block</span>;</pre>
                        <pre><span class="lnum">  66:  </span>    <span class="attr">width</span>: <span class="kwrd">150px</span>;</pre>
                        <pre class="alt"><span class="lnum">  67:  </span>    <span class="attr">height</span>: <span class="kwrd">100%</span>;</pre>
                        <pre><span class="lnum">  68:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre class="alt"><span class="lnum">  69:  </span>    <span class="attr">padding</span>: <span class="kwrd">5px 0 0 20px</span>;</pre>
                        <pre><span class="lnum">  70:  </span>    <span class="attr">font-size</span>: <span class="kwrd">14px</span>;</pre>
                        <pre class="alt"><span class="lnum">  71:  </span>    <span class="attr">color</span>: <span class="kwrd">#333333</span>;</pre>
                        <pre><span class="lnum">  72:  </span>}</pre>
                        <pre class="alt"><span class="lnum">  73:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  74:  </span><span class="str">.regular__ctrls     .ffield__lbl2</span> {</pre>
                        <pre class="alt"><span class="lnum">  75:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre><span class="lnum">  76:  </span>    <span class="attr">font-size</span>: <span class="kwrd">14px</span>;</pre>
                        <pre class="alt"><span class="lnum">  77:  </span>    <span class="attr">padding</span>: <span class="kwrd">5px 12px 0 22px</span>;</pre>
                        <pre><span class="lnum">  78:  </span>    <span class="attr">color</span>: <span class="kwrd">#333333</span>;</pre>
                        <pre class="alt"><span class="lnum">  79:  </span>}</pre>
                        <pre><span class="lnum">  80:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  81:  </span><span class="str">.regular__ctrls input</span>[type=<span class="kwrd">"text"</span>] {</pre>
                        <pre><span class="lnum">  82:  </span>    <span class="attr">width</span>: <span class="kwrd">128px</span>;</pre>
                        <pre class="alt"><span class="lnum">  83:  </span>    <span class="attr">display</span>: <span class="kwrd">inline</span>-<span class="kwrd">block</span>;</pre>
                        <pre><span class="lnum">  84:  </span>    <span class="attr">height</span>: <span class="kwrd">23px</span>;</pre>
                        <pre class="alt"><span class="lnum">  85:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre><span class="lnum">  86:  </span>    <span class="attr">padding</span>: <span class="kwrd">0</span>;</pre>
                        <pre class="alt"><span class="lnum">  87:  </span>    <span class="attr">margin</span>: <span class="kwrd">0</span>;</pre>
                        <pre><span class="lnum">  88:  </span>    <span class="attr">font-family</span>:<span class="kwrd">&nbsp;Helvetica,&nbsp;Arial</span>;</pre>
                        <pre class="alt"><span class="lnum">  89:  </span>    <span class="attr">font-size</span>: <span class="kwrd">13px !important</span>;</pre>
                        <pre><span class="lnum">  90:  </span>    <span class="attr">text-indent</span>: <span class="kwrd">8px</span>;</pre>
                        <pre class="alt"><span class="lnum">  91:  </span>    <span class="attr">line-height</span>: <span class="kwrd">15px</span>;</pre>
                        <pre><span class="lnum">  92:  </span>    <span class="attr">border</span>: <span class="kwrd">1px solid #C2C2C2</span>;</pre>
                        <pre class="alt"><span class="lnum">  93:  </span>    <span class="attr">border-top</span>: <span class="kwrd">1px solid #919292</span>;</pre>
                        <pre><span class="lnum">  94:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">3px</span>;</pre>
                        <pre class="alt"><span class="lnum">  95:  </span>    box-shadow: <span class="kwrd">0 1px 1px #e5e5e5 inset</span>;</pre>
                        <pre><span class="lnum">  96:  </span>    <span class="attr">outline</span>: <span class="kwrd">none</span>;</pre>
                        <pre class="alt"><span class="lnum">  97:  </span>}</pre>
                        <pre><span class="lnum">  98:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  99:  </span><span class="str">.regular__ctrls input</span>[type=<span class="kwrd">"text"</span>]<span class="str">.small</span> {</pre>
                        <pre><span class="lnum"> 100:  </span>    <span class="attr">width</span>: <span class="kwrd">150px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 101:  </span>}</pre>
                        <pre><span class="lnum"> 102:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 103:  </span><span class="str">.regular__ctrls input</span>[type=<span class="kwrd">"text"</span>]<span class="str">.long</span> {</pre>
                        <pre><span class="lnum"> 104:  </span>    <span class="attr">width</span>: <span class="kwrd">490px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 105:  </span>}</pre>
                        <pre><span class="lnum"> 106:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 107:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 108:  </span><span class="rem">/*&nbsp;Addition&nbsp;*/</span></pre>
                        <pre class="alt"><span class="lnum"> 109:  </span><span class="str">.addition</span>{</pre>
                        <pre><span class="lnum"> 110:  </span>    <span class="attr">margin-left</span>: <span class="kwrd">170px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 111:  </span>    <span class="attr">width</span>: <span class="kwrd">490px</span>;</pre>
                        <pre><span class="lnum"> 112:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 113:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 114:  </span><span class="str">.addition .block</span>{</pre>
                        <pre class="alt"><span class="lnum"> 115:  </span>    <span class="attr">display</span>:<span class="str"> block</span>;</pre>
                        <pre><span class="lnum"> 116:  </span>    <span class="attr">height</span>: <span class="kwrd">150px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 117:  </span>    <span class="attr">padding</span>: <span class="kwrd">10px</span>;</pre>
                        <pre><span class="lnum"> 118:  </span>    <span class="attr">font-size</span>: <span class="kwrd">15px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 119:  </span>    <span class="attr">border</span>-radius: <span class="kwrd">10px</span>;</pre>
                        <pre><span class="lnum"> 120:  </span>    <span class="attr">margin-bottom</span>: <span class="kwrd">20px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 121:  </span>    <span class="attr">background-color</span>: rgba(<span class="rem">0,&nbsp;0,&nbsp;0,&nbsp;0.06</span>);</pre>
                        <pre><span class="lnum"> 122:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 123:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 124:  </span><span class="str">.addition .block</span>:nth-child(<span class="rem">1</span>){</pre>
                        <pre class="alt"><span class="lnum"> 125:  </span>    <span class="attr">float</span>: <span class="kwrd">left</span>;</pre>
                        <pre><span class="lnum"> 126:  </span>    <span class="attr">width</span>: <span class="kwrd">200px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 127:  </span>}</pre>
                        <pre><span class="lnum"> 128:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 129:  </span><span class="str">.addition .block</span>:nth-child(<span class="rem">2</span>){</pre>
                        <pre><span class="lnum"> 130:  </span>    <span class="attr">float</span>: <span class="kwrd">right</span>;</pre>
                        <pre class="alt"><span class="lnum"> 131:  </span>    <span class="attr">width</span>: <span class="kwrd">240px</span>;</pre>
                        <pre><span class="lnum"> 132:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 133:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 134:  </span><span class="str">.addition p</span>{</pre>
                        <pre class="alt"><span class="lnum"> 135:  </span>    -webkit-<span class="attr">margin</span>-before: <span class="kwrd">0</span>;</pre>
                        <pre><span class="lnum"> 136:  </span>    -webkit-<span class="attr">margin</span>-after: <span class="kwrd">0</span>;</pre>
                        <pre class="alt"><span class="lnum"> 137:  </span>}</pre>
                        <pre><span class="lnum"> 138:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 139:  </span><span class="str">.addition .title</span>{</pre>
                        <pre><span class="lnum"> 140:  </span>    <span class="attr">font-weight</span>: <span class="kwrd">bold</span>;</pre>
                        <pre class="alt"><span class="lnum"> 141:  </span>    <span class="attr">margin-bottom</span>: <span class="kwrd">10px</span>;</pre>
                        <pre><span class="lnum"> 142:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 143:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 144:  </span><span class="str">.addition ul</span>{</pre>
                        <pre class="alt"><span class="lnum"> 145:  </span>    <span class="attr">margin</span>: <span class="kwrd">0</span>;</pre>
                        <pre><span class="lnum"> 146:  </span>    <span class="attr">padding</span>: <span class="kwrd">0</span>;</pre>
                        <pre class="alt"><span class="lnum"> 147:  </span>    <span class="attr">list-style-type</span>: <span class="kwrd">none</span>;</pre>
                        <pre><span class="lnum"> 148:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 149:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 150:  </span><span class="str">.addition .name</span>{</pre>
                        <pre class="alt"><span class="lnum"> 151:  </span>    <span class="attr">font-style</span>: <span class="kwrd">italic</span>;</pre>
                        <pre><span class="lnum"> 152:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 153:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 154:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 155:  </span><span class="rem">/*&nbsp;Custom&nbsp;Autocomplete&nbsp;*/</span></pre>
                        <pre><span class="lnum"> 156:  </span><span class="str">.ui-autocomplete</span> {</pre>
                        <pre class="alt"><span class="lnum"> 157:  </span>    <span class="attr">background</span>: <span class="kwrd">#ffffff</span>;</pre>
                        <pre><span class="lnum"> 158:  </span>    <span class="attr">border</span>: <span class="kwrd">1px solid #B1B1B1</span>;</pre>
                        <pre class="alt"><span class="lnum"> 159:  </span>    <span class="attr">overflow</span>-y: <span class="kwrd">auto</span>;</pre>
                        <pre><span class="lnum"> 160:  </span>    <span class="attr">max-height</span>: <span class="kwrd">400px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 161:  </span>    <span class="attr">max-width</span>: <span class="kwrd">490px</span>;</pre>
                        <pre><span class="lnum"> 162:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 163:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 164:  </span><span class="str">.ui-autocomplete li</span> {</pre>
                        <pre class="alt"><span class="lnum"> 165:  </span>    <span class="attr">font-size</span>: <span class="kwrd">13px</span>;</pre>
                        <pre><span class="lnum"> 166:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 167:  </span>    <span class="attr">border-top</span>: <span class="kwrd">1px solid #E2E2E2</span>;</pre>
                        <pre><span class="lnum"> 168:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 169:  </span>}</pre>
                        <pre><span class="lnum"> 170:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 171:  </span><span class="str">.ui-autocomplete li:first-child</span> {</pre>
                        <pre><span class="lnum"> 172:  </span>    <span class="attr">border</span>: <span class="kwrd">none</span>;</pre>
                        <pre class="alt"><span class="lnum"> 173:  </span>}</pre>
                        <pre><span class="lnum"> 174:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 175:  </span><span class="str">.ui-autocomplete li a</span> {</pre>
                        <pre><span class="lnum"> 176:  </span>    <span class="attr">display</span>:<span class="str"> block</span>;</pre>
                        <pre class="alt"><span class="lnum"> 177:  </span>    <span class="attr">padding</span>: <span class="kwrd">0 10px</span>;</pre>
                        <pre><span class="lnum"> 178:  </span>    <span class="attr">line-height</span>: <span class="kwrd">23px</span>;</pre>
                        <pre class="alt"><span class="lnum"> 179:  </span>}</pre>
                        <pre><span class="lnum"> 180:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 181:  </span><span class="str">.ui-autocomplete li:hover a</span>,</pre>
                        <pre><span class="lnum"> 182:  </span><span class="str">.ui-autocomplete li a:hover</span> {</pre>
                        <pre class="alt"><span class="lnum"> 183:  </span>    <span class="attr">font-weight</span>: <span class="kwrd">normal</span>;</pre>
                        <pre><span class="lnum"> 184:  </span>    <span class="attr">color</span>: <span class="kwrd">#333333</span>;</pre>
                        <pre class="alt"><span class="lnum"> 185:  </span>}</pre>
                        <pre><span class="lnum"> 186:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 187:  </span><span class="str">.ui-autocomplete li .ac-s</span> {</pre>
                        <pre><span class="lnum"> 188:  </span>    <span class="attr">color</span>: <span class="kwrd">#52A3B6</span>;</pre>
                        <pre class="alt"><span class="lnum"> 189:  </span>}</pre>
                        <pre><span class="lnum"> 190:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 191:  </span><span class="str">.ui-autocomplete li .ac-s2</span> {</pre>
                        <pre><span class="lnum"> 192:  </span>    <span class="attr">color</span>: <span class="kwrd">#333333</span>;</pre>
                        <pre class="alt"><span class="lnum"> 193:  </span>}</pre>
                        <pre><span class="lnum"> 194:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 195:  </span><span class="str">.ui-autocomplete li .ac-s</span>,</pre>
                        <pre><span class="lnum"> 196:  </span><span class="str">.ui-autocomplete li .ac-s2</span> {</pre>
                        <pre class="alt"><span class="lnum"> 197:  </span>    <span class="attr">font-weight</span>: <span class="kwrd">bold</span>;</pre>
                        <pre><span class="lnum"> 198:  </span>}</pre>
                        <pre class="alt"><span class="lnum"> 199:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 200:  </span><span class="str">.ui-autocomplete li .ac-st</span> {</pre>
                        <pre class="alt"><span class="lnum"> 201:  </span>    <span class="attr">color</span>: <span class="kwrd">#AAAAAA</span>;</pre>
                        <pre><span class="lnum"> 202:  </span>} </pre>
                    </ol>
                </div>
            </div>
            <div id="tabs-4-4">
                <div class="scme">
                    <a href="js/example4.js" target="_blank">Source</a>
                    <ol><pre class="alt"><span class="lnum">   1:  </span>(<span class="kwrd">function</span>($){</pre>
                        <pre><span class="lnum">   2:  </span>    $(<span class="kwrd">function</span>() {</pre>
                        <pre class="alt"><span class="lnum">   3:  </span>        <span class="kwrd">var</span> token = <span class="str">'51dfe5d42fb2b43e3300006e'</span>;</pre>
                        <pre><span class="lnum">   4:  </span>        <span class="kwrd">var</span> key = <span class="str">'86a2c2a06f1b2451a87d05512cc2c3edfdf41969'</span>;        </pre>
                        <pre class="alt"><span class="lnum">   5:  </span>&nbsp;</pre>
                        <pre><span class="lnum">   6:  </span>        <span class="kwrd">var</span> city = $( <span class="str">'[name="city"]'</span> );</pre>
                        <pre class="alt"><span class="lnum">   7:  </span>        <span class="kwrd">var</span> street = $( <span class="str">'[name="street"]'</span> );</pre>
                        <pre><span class="lnum">   8:  </span>        <span class="kwrd">var</span> building = $( <span class="str">'[name="building"]'</span> );</pre>
                        <pre class="alt"><span class="lnum">   9:  </span>        <span class="kwrd">var</span> buildingAdd = $( <span class="str">'[name="building-add"]'</span> );</pre>
                        <pre><span class="lnum">  10:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  11:  </span>        <span class="kwrd">var</span> map = <span class="kwrd">null</span>;</pre>
                        <pre><span class="lnum">  12:  </span>        <span class="kwrd">var</span> placemark = <span class="kwrd">null</span>;</pre>
                        <pre class="alt"><span class="lnum">  13:  </span>        <span class="kwrd">var</span> map_created = <span class="kwrd">false</span>;</pre>
                        <pre><span class="lnum">  14:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  15:  </span>        <span class="rem">//&nbsp;Формирует&nbsp;подписи&nbsp;в&nbsp;autocomplete</span></pre>
                        <pre><span class="lnum">  16:  </span>        <span class="kwrd">var</span> Label = <span class="kwrd">function</span>( obj, query ){</pre>
                        <pre class="alt"><span class="lnum">  17:  </span>            <span class="kwrd">var</span> label = <span class="str">''</span>;</pre>
                        <pre><span class="lnum">  18:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  19:  </span>            <span class="kwrd">if</span>(obj.name){</pre>
                        <pre><span class="lnum">  20:  </span>                <span class="kwrd">if</span>(obj.typeShort){</pre>
                        <pre class="alt"><span class="lnum">  21:  </span>                    label += <span class="str">'&lt;span&nbsp;class="ac-s2"&gt;'</span> + obj.typeShort + <span class="str">'.&nbsp;'</span> + <span class="str">'&lt;/span&gt;'</span>;</pre>
                        <pre><span class="lnum">  22:  </span>                }</pre>
                        <pre class="alt"><span class="lnum">  23:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  24:  </span>                <span class="kwrd">if</span>(query.length &lt; obj.name.length){</pre>
                        <pre class="alt"><span class="lnum">  25:  </span>                    label += <span class="str">'&lt;span&nbsp;class="ac-s"&gt;'</span> + obj.name.substr(<span class="str">0</span>, query.length) + <span class="str">'&lt;/span&gt;'</span>;</pre>
                        <pre><span class="lnum">  26:  </span>                    label += <span class="str">'&lt;span&nbsp;class="ac-s2"&gt;'</span> + obj.name.substr(query.length, obj.name.length - query.length) + <span class="str">'&lt;/span&gt;'</span>;</pre>
                        <pre class="alt"><span class="lnum">  27:  </span>                } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum">  28:  </span>                    label += <span class="str">'&lt;span&nbsp;class="ac-s"&gt;'</span> + obj.name + <span class="str">'&lt;/span&gt;'</span>;</pre>
                        <pre class="alt"><span class="lnum">  29:  </span>                }</pre>
                        <pre><span class="lnum">  30:  </span>            }</pre>
                        <pre class="alt"><span class="lnum">  31:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  32:  </span>            <span class="kwrd">if</span>(obj.parents){</pre>
                        <pre class="alt"><span class="lnum">  33:  </span>                <span class="kwrd">for</span>(<span class="kwrd">var</span> k = obj.parents.length-<span class="str">1</span>; k&gt;-<span class="str">1</span>; k--){</pre>
                        <pre><span class="lnum">  34:  </span>                    <span class="kwrd">var</span> parent = obj.parents[k];</pre>
                        <pre class="alt"><span class="lnum">  35:  </span>                    <span class="kwrd">if</span>(parent.name){</pre>
                        <pre><span class="lnum">  36:  </span>                        <span class="kwrd">if</span>(label) label += <span class="str">'&lt;span&nbsp;class="ac-st"&gt;,&nbsp;&lt;/span&gt;'</span>;</pre>
                        <pre class="alt"><span class="lnum">  37:  </span>                        label += <span class="str">'&lt;span&nbsp;class="ac-st"&gt;'</span> + parent.name + <span class="str">'&nbsp;'</span> + parent.typeShort + <span class="str">'.&lt;/span&gt;'</span>;</pre>
                        <pre><span class="lnum">  38:  </span>                    }</pre>
                        <pre class="alt"><span class="lnum">  39:  </span>                }</pre>
                        <pre><span class="lnum">  40:  </span>            }</pre>
                        <pre class="alt"><span class="lnum">  41:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  42:  </span>            <span class="kwrd">return</span> label;</pre>
                        <pre class="alt"><span class="lnum">  43:  </span>        };</pre>
                        <pre><span class="lnum">  44:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  45:  </span>        <span class="rem">//&nbsp;Обновляет&nbsp;карту</span></pre>
                        <pre><span class="lnum">  46:  </span>        <span class="kwrd">var</span> MapUpdate = <span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum">  47:  </span>            <span class="kwrd">var</span> zoom = <span class="str">12</span>;</pre>
                        <pre><span class="lnum">  48:  </span>            <span class="kwrd">var</span> address = <span class="str">''</span>;</pre>
                        <pre class="alt"><span class="lnum">  49:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  50:  </span>            <span class="kwrd">var</span> cityVal = $.trim(city.val());</pre>
                        <pre class="alt"><span class="lnum">  51:  </span>            <span class="kwrd">if</span>(cityVal){</pre>
                        <pre><span class="lnum">  52:  </span>                <span class="kwrd">var</span> cityObj = city.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre class="alt"><span class="lnum">  53:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum">  54:  </span>                address += ( cityObj ? (cityObj.typeShort + <span class="str">'&nbsp;'</span>) : <span class="str">''</span> ) + cityVal;</pre>
                        <pre class="alt"><span class="lnum">  55:  </span>                zoom = <span class="str">12</span>;</pre>
                        <pre><span class="lnum">  56:  </span>            }</pre>
                        <pre class="alt"><span class="lnum">  57:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  58:  </span>            <span class="kwrd">var</span> streetVal = $.trim(street.val());</pre>
                        <pre class="alt"><span class="lnum">  59:  </span>            <span class="kwrd">if</span>(streetVal){</pre>
                        <pre><span class="lnum">  60:  </span>                <span class="kwrd">var</span> streetObj = street.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre class="alt"><span class="lnum">  61:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum">  62:  </span>                address += ( streetObj ? (streetObj.typeShort + <span class="str">'&nbsp;'</span>) : <span class="str">''</span> ) + streetVal;</pre>
                        <pre class="alt"><span class="lnum">  63:  </span>                zoom = <span class="str">14</span>;</pre>
                        <pre><span class="lnum">  64:  </span>            }</pre>
                        <pre class="alt"><span class="lnum">  65:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  66:  </span>            <span class="kwrd">var</span> buildingVal = $.trim(building.val());</pre>
                        <pre class="alt"><span class="lnum">  67:  </span>            <span class="kwrd">if</span>(buildingVal){</pre>
                        <pre><span class="lnum">  68:  </span>                <span class="kwrd">var</span> buildingObj = building.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre class="alt"><span class="lnum">  69:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum">  70:  </span>                address += <span class="str">'д.&nbsp;'</span> + buildingVal;</pre>
                        <pre class="alt"><span class="lnum">  71:  </span>                zoom = <span class="str">16</span>;</pre>
                        <pre><span class="lnum">  72:  </span>            }</pre>
                        <pre class="alt"><span class="lnum">  73:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  74:  </span>            <span class="kwrd">var</span> buildingAddVal = $.trim(buildingAdd.val());</pre>
                        <pre class="alt"><span class="lnum">  75:  </span>            <span class="kwrd">if</span>(buildingAddVal){</pre>
                        <pre><span class="lnum">  76:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre class="alt"><span class="lnum">  77:  </span>                address += buildingAddVal;</pre>
                        <pre><span class="lnum">  78:  </span>                zoom = <span class="str">16</span>;</pre>
                        <pre class="alt"><span class="lnum">  79:  </span>            }</pre>
                        <pre><span class="lnum">  80:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum">  81:  </span>            <span class="kwrd">if</span>(address &amp;&amp; map_created){</pre>
                        <pre><span class="lnum">  82:  </span>                <span class="kwrd">var</span> geocode = ymaps.geocode(address);</pre>
                        <pre class="alt"><span class="lnum">  83:  </span>                geocode.then(<span class="kwrd">function</span>(res){</pre>
                        <pre><span class="lnum">  84:  </span>                    map.geoObjects.each(<span class="kwrd">function</span> (geoObject) {</pre>
                        <pre class="alt"><span class="lnum">  85:  </span>                            map.geoObjects.remove(geoObject);</pre>
                        <pre><span class="lnum">  86:  </span>                    });</pre>
                        <pre class="alt"><span class="lnum">  87:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  88:  </span>                    <span class="kwrd">var</span> position = res.geoObjects.get(<span class="str">0</span>).geometry.getCoordinates();</pre>
                        <pre class="alt"><span class="lnum">  89:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  90:  </span>                    placemark = <span class="kwrd">new</span> ymaps.Placemark(position, {}, {});</pre>
                        <pre class="alt"><span class="lnum">  91:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  92:  </span>                    map.geoObjects.add(placemark);</pre>
                        <pre class="alt"><span class="lnum">  93:  </span>                    map.setCenter(position, zoom);</pre>
                        <pre><span class="lnum">  94:  </span>                });</pre>
                        <pre class="alt"><span class="lnum">  95:  </span>            }</pre>
                        <pre><span class="lnum">  96:  </span>        }</pre>
                        <pre class="alt"><span class="lnum">  97:  </span>&nbsp;</pre>
                        <pre><span class="lnum">  98:  </span>        <span class="rem">//&nbsp;Обновляет&nbsp;текстовое&nbsp;представление&nbsp;адреса</span></pre>
                        <pre class="alt"><span class="lnum">  99:  </span>        <span class="kwrd">var</span> AddressUpdate = <span class="kwrd">function</span>(){</pre>
                        <pre><span class="lnum"> 100:  </span>            <span class="kwrd">var</span> address = <span class="str">''</span>;</pre>
                        <pre class="alt"><span class="lnum"> 101:  </span>            <span class="kwrd">var</span> zip = <span class="str">''</span>;</pre>
                        <pre><span class="lnum"> 102:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 103:  </span>            <span class="kwrd">var</span> cityVal = $.trim(city.val());</pre>
                        <pre><span class="lnum"> 104:  </span>            <span class="kwrd">if</span>($.trim(city.val())){</pre>
                        <pre class="alt"><span class="lnum"> 105:  </span>                <span class="kwrd">var</span> cityObj = city.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre><span class="lnum"> 106:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 107:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum"> 108:  </span>                address += ( cityObj ? (cityObj.typeShort + <span class="str">'.&nbsp;'</span>) : <span class="str">'г.&nbsp;'</span> ) + cityVal;</pre>
                        <pre class="alt"><span class="lnum"> 109:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 110:  </span>                <span class="kwrd">if</span>(cityObj.zip) zip = cityObj.zip;</pre>
                        <pre class="alt"><span class="lnum"> 111:  </span>            }</pre>
                        <pre><span class="lnum"> 112:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 113:  </span>            <span class="kwrd">var</span> streetVal = $.trim(street.val());</pre>
                        <pre><span class="lnum"> 114:  </span>            <span class="kwrd">if</span>(streetVal){</pre>
                        <pre class="alt"><span class="lnum"> 115:  </span>                <span class="kwrd">var</span> streetObj = street.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre><span class="lnum"> 116:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 117:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum"> 118:  </span>                address += ( streetObj ? (streetObj.typeShort + <span class="str">'.&nbsp;'</span>) : <span class="str">'ул.&nbsp;'</span> ) + streetVal;</pre>
                        <pre class="alt"><span class="lnum"> 119:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 120:  </span>                <span class="kwrd">if</span>(streetObj.zip) zip = streetObj.zip;</pre>
                        <pre class="alt"><span class="lnum"> 121:  </span>            }</pre>
                        <pre><span class="lnum"> 122:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 123:  </span>            <span class="kwrd">var</span> buildingVal = $.trim(building.val());</pre>
                        <pre><span class="lnum"> 124:  </span>            <span class="kwrd">if</span>(buildingVal){</pre>
                        <pre class="alt"><span class="lnum"> 125:  </span>                <span class="kwrd">var</span> buildingObj = building.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre><span class="lnum"> 126:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 127:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum"> 128:  </span>                address += <span class="str">'д.&nbsp;'</span> + buildingVal;</pre>
                        <pre class="alt"><span class="lnum"> 129:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 130:  </span>                <span class="kwrd">if</span>(buildingObj.zip) zip = buildingObj.zip;</pre>
                        <pre class="alt"><span class="lnum"> 131:  </span>            }</pre>
                        <pre><span class="lnum"> 132:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 133:  </span>            <span class="kwrd">var</span> buildingAddVal = $.trim(buildingAdd.val());</pre>
                        <pre><span class="lnum"> 134:  </span>            <span class="kwrd">if</span>(buildingAddVal){</pre>
                        <pre class="alt"><span class="lnum"> 135:  </span>                <span class="kwrd">if</span>(address) address += <span class="str">',&nbsp;'</span>;</pre>
                        <pre><span class="lnum"> 136:  </span>                address += <span class="str">'к.&nbsp;'</span> + buildingAddVal;</pre>
                        <pre class="alt"><span class="lnum"> 137:  </span>            }</pre>
                        <pre><span class="lnum"> 138:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 139:  </span>            address = (zip ? zip + <span class="str">',&nbsp;'</span> : <span class="str">''</span>) + address;</pre>
                        <pre><span class="lnum"> 140:  </span>            $(<span class="str">'#address'</span>).text(address);</pre>
                        <pre class="alt"><span class="lnum"> 141:  </span>        }</pre>
                        <pre><span class="lnum"> 142:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 143:  </span>        <span class="rem">//&nbsp;Обновляет&nbsp;лог&nbsp;текущего&nbsp;выбранного&nbsp;объекта</span></pre>
                        <pre><span class="lnum"> 144:  </span>        <span class="kwrd">var</span> Log = <span class="kwrd">function</span>(obj){</pre>
                        <pre class="alt"><span class="lnum"> 145:  </span>            <span class="kwrd">var</span> logId = $(<span class="str">'#id'</span>);</pre>
                        <pre><span class="lnum"> 146:  </span>            <span class="kwrd">if</span>(obj.id){</pre>
                        <pre class="alt"><span class="lnum"> 147:  </span>                logId.find(<span class="str">'.value'</span>).text(obj.id);</pre>
                        <pre><span class="lnum"> 148:  </span>                logId.show();</pre>
                        <pre class="alt"><span class="lnum"> 149:  </span>            } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 150:  </span>                logId.hide();</pre>
                        <pre class="alt"><span class="lnum"> 151:  </span>            }</pre>
                        <pre><span class="lnum"> 152:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 153:  </span>            <span class="kwrd">var</span> logName = $(<span class="str">'#name'</span>);</pre>
                        <pre><span class="lnum"> 154:  </span>            <span class="kwrd">if</span>(obj.name){</pre>
                        <pre class="alt"><span class="lnum"> 155:  </span>                logName.find(<span class="str">'.value'</span>).text(obj.name);</pre>
                        <pre><span class="lnum"> 156:  </span>                logName.show();</pre>
                        <pre class="alt"><span class="lnum"> 157:  </span>            } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 158:  </span>                logName.hide();</pre>
                        <pre class="alt"><span class="lnum"> 159:  </span>            }</pre>
                        <pre><span class="lnum"> 160:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 161:  </span>            <span class="kwrd">var</span> logZip = $(<span class="str">'#zip'</span>);</pre>
                        <pre><span class="lnum"> 162:  </span>            <span class="kwrd">if</span>(obj.zip){</pre>
                        <pre class="alt"><span class="lnum"> 163:  </span>                logZip.find(<span class="str">'.value'</span>).text(obj.zip);</pre>
                        <pre><span class="lnum"> 164:  </span>                logZip.show();</pre>
                        <pre class="alt"><span class="lnum"> 165:  </span>            } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 166:  </span>                logZip.hide();</pre>
                        <pre class="alt"><span class="lnum"> 167:  </span>            }</pre>
                        <pre><span class="lnum"> 168:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 169:  </span>            <span class="kwrd">var</span> logType = $(<span class="str">'#type'</span>);</pre>
                        <pre><span class="lnum"> 170:  </span>            <span class="kwrd">if</span>(obj.type){</pre>
                        <pre class="alt"><span class="lnum"> 171:  </span>                logType.find(<span class="str">'.value'</span>).text(obj.type);</pre>
                        <pre><span class="lnum"> 172:  </span>                logType.show();</pre>
                        <pre class="alt"><span class="lnum"> 173:  </span>            } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 174:  </span>                logType.hide();</pre>
                        <pre class="alt"><span class="lnum"> 175:  </span>            }</pre>
                        <pre><span class="lnum"> 176:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 177:  </span>            <span class="kwrd">var</span> logTypeShort = $(<span class="str">'#type_short'</span>);</pre>
                        <pre><span class="lnum"> 178:  </span>            <span class="kwrd">if</span>(obj.typeShort){</pre>
                        <pre class="alt"><span class="lnum"> 179:  </span>                logTypeShort.find(<span class="str">'.value'</span>).text(obj.typeShort);</pre>
                        <pre><span class="lnum"> 180:  </span>                logTypeShort.show();</pre>
                        <pre class="alt"><span class="lnum"> 181:  </span>            } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 182:  </span>                logTypeShort.hide();</pre>
                        <pre class="alt"><span class="lnum"> 183:  </span>            }</pre>
                        <pre><span class="lnum"> 184:  </span>        }</pre>
                        <pre class="alt"><span class="lnum"> 185:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 186:  </span>        city.kladr({</pre>
                        <pre class="alt"><span class="lnum"> 187:  </span>            token: token,</pre>
                        <pre><span class="lnum"> 188:  </span>            key: key,</pre>
                        <pre class="alt"><span class="lnum"> 189:  </span>            type: $.ui.kladrObjectType.CITY,</pre>
                        <pre><span class="lnum"> 190:  </span>            withParents: <span class="kwrd">true</span>,</pre>
                        <pre class="alt"><span class="lnum"> 191:  </span>            label: Label,</pre>
                        <pre><span class="lnum"> 192:  </span>            select: <span class="kwrd">function</span>( <span class="kwrd">event</span>, ui ) {</pre>
                        <pre class="alt"><span class="lnum"> 193:  </span>                city.data( <span class="str">"kladr-obj"</span>, ui.item.obj );</pre>
                        <pre><span class="lnum"> 194:  </span>                city.parent().find( <span class="str">'label'</span> ).text( ui.item.obj.type );</pre>
                        <pre class="alt"><span class="lnum"> 195:  </span>                street.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: ui.item.obj.id } );</pre>
                        <pre><span class="lnum"> 196:  </span>                building.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: ui.item.obj.id } );</pre>
                        <pre class="alt"><span class="lnum"> 197:  </span>                Log(ui.item.obj);</pre>
                        <pre><span class="lnum"> 198:  </span>                AddressUpdate();</pre>
                        <pre class="alt"><span class="lnum"> 199:  </span>                MapUpdate();                </pre>
                        <pre><span class="lnum"> 200:  </span>            }</pre>
                        <pre class="alt"><span class="lnum"> 201:  </span>        });</pre>
                        <pre><span class="lnum"> 202:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 203:  </span>        street.kladr({</pre>
                        <pre><span class="lnum"> 204:  </span>            token: token,</pre>
                        <pre class="alt"><span class="lnum"> 205:  </span>            key: key,</pre>
                        <pre><span class="lnum"> 206:  </span>            type: $.ui.kladrObjectType.STREET,</pre>
                        <pre class="alt"><span class="lnum"> 207:  </span>            label: Label,</pre>
                        <pre><span class="lnum"> 208:  </span>            select: <span class="kwrd">function</span>( <span class="kwrd">event</span>, ui ) {</pre>
                        <pre class="alt"><span class="lnum"> 209:  </span>                street.data( <span class="str">"kladr-obj"</span>, ui.item.obj );</pre>
                        <pre><span class="lnum"> 210:  </span>                street.parent().find( <span class="str">'label'</span> ).text( ui.item.obj.type );</pre>
                        <pre class="alt"><span class="lnum"> 211:  </span>                building.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.STREET, parentId: ui.item.obj.id } );</pre>
                        <pre><span class="lnum"> 212:  </span>                Log(ui.item.obj);</pre>
                        <pre class="alt"><span class="lnum"> 213:  </span>                AddressUpdate();</pre>
                        <pre><span class="lnum"> 214:  </span>                MapUpdate();</pre>
                        <pre class="alt"><span class="lnum"> 215:  </span>            }</pre>
                        <pre><span class="lnum"> 216:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 217:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 218:  </span>        building.kladr({</pre>
                        <pre class="alt"><span class="lnum"> 219:  </span>            token: token,</pre>
                        <pre><span class="lnum"> 220:  </span>            key: key,</pre>
                        <pre class="alt"><span class="lnum"> 221:  </span>            type: $.ui.kladrObjectType.BUILDING,</pre>
                        <pre><span class="lnum"> 222:  </span>            label: Label,</pre>
                        <pre class="alt"><span class="lnum"> 223:  </span>            select: <span class="kwrd">function</span>( <span class="kwrd">event</span>, ui ) {</pre>
                        <pre><span class="lnum"> 224:  </span>                building.data( <span class="str">"kladr-obj"</span>, ui.item.obj );</pre>
                        <pre class="alt"><span class="lnum"> 225:  </span>                Log(ui.item.obj);</pre>
                        <pre><span class="lnum"> 226:  </span>                AddressUpdate();</pre>
                        <pre class="alt"><span class="lnum"> 227:  </span>                MapUpdate();</pre>
                        <pre><span class="lnum"> 228:  </span>            }</pre>
                        <pre class="alt"><span class="lnum"> 229:  </span>        });</pre>
                        <pre><span class="lnum"> 230:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 231:  </span>        city.change(<span class="kwrd">function</span>(){</pre>
                        <pre><span class="lnum"> 232:  </span>            $.kladrCheck({</pre>
                        <pre class="alt"><span class="lnum"> 233:  </span>                token: token,</pre>
                        <pre><span class="lnum"> 234:  </span>                key: key,</pre>
                        <pre class="alt"><span class="lnum"> 235:  </span>                value: city.val(),</pre>
                        <pre><span class="lnum"> 236:  </span>                type: $.ui.kladrObjectType.CITY,</pre>
                        <pre class="alt"><span class="lnum"> 237:  </span>            }, <span class="kwrd">function</span>(obj){</pre>
                        <pre><span class="lnum"> 238:  </span>                <span class="kwrd">if</span>(!obj) {</pre>
                        <pre class="alt"><span class="lnum"> 239:  </span>                    city.css(<span class="str">'color'</span>, <span class="str">'red'</span>);</pre>
                        <pre><span class="lnum"> 240:  </span>                } <span class="kwrd">else</span> {</pre>
                        <pre class="alt"><span class="lnum"> 241:  </span>                    city.val(obj.name);</pre>
                        <pre><span class="lnum"> 242:  </span>                    city.data( <span class="str">"kladr-obj"</span>, obj );</pre>
                        <pre class="alt"><span class="lnum"> 243:  </span>                    city.parent().find( <span class="str">'label'</span> ).text( obj.type );</pre>
                        <pre><span class="lnum"> 244:  </span>                    street.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: obj.id } );</pre>
                        <pre class="alt"><span class="lnum"> 245:  </span>                    building.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.CITY, parentId: obj.id } );</pre>
                        <pre><span class="lnum"> 246:  </span>                    Log(obj);</pre>
                        <pre class="alt"><span class="lnum"> 247:  </span>                    AddressUpdate();</pre>
                        <pre><span class="lnum"> 248:  </span>                    MapUpdate(); </pre>
                        <pre class="alt"><span class="lnum"> 249:  </span>                }         </pre>
                        <pre><span class="lnum"> 250:  </span>            });</pre>
                        <pre class="alt"><span class="lnum"> 251:  </span>        });</pre>
                        <pre><span class="lnum"> 252:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 253:  </span>        street.change(<span class="kwrd">function</span>(){</pre>
                        <pre><span class="lnum"> 254:  </span>            <span class="kwrd">var</span> query = {</pre>
                        <pre class="alt"><span class="lnum"> 255:  </span>                token: token,</pre>
                        <pre><span class="lnum"> 256:  </span>                key: key,</pre>
                        <pre class="alt"><span class="lnum"> 257:  </span>                value: street.val(),</pre>
                        <pre><span class="lnum"> 258:  </span>                type: $.ui.kladrObjectType.STREET,</pre>
                        <pre class="alt"><span class="lnum"> 259:  </span>            };</pre>
                        <pre><span class="lnum"> 260:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 261:  </span>            <span class="kwrd">var</span> cityObj = city.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre><span class="lnum"> 262:  </span>            <span class="kwrd">if</span>(cityObj){</pre>
                        <pre class="alt"><span class="lnum"> 263:  </span>                query[<span class="str">'parentType'</span>] = $.ui.kladrObjectType.CITY;</pre>
                        <pre><span class="lnum"> 264:  </span>                query[<span class="str">'parentId'</span>] = cityObj.id;</pre>
                        <pre class="alt"><span class="lnum"> 265:  </span>            }            </pre>
                        <pre><span class="lnum"> 266:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 267:  </span>            $.kladrCheck(query, <span class="kwrd">function</span>(obj){</pre>
                        <pre><span class="lnum"> 268:  </span>                <span class="kwrd">if</span>(!obj) {</pre>
                        <pre class="alt"><span class="lnum"> 269:  </span>                    street.css(<span class="str">'color'</span>, <span class="str">'red'</span>);</pre>
                        <pre><span class="lnum"> 270:  </span>                } <span class="kwrd">else</span> {</pre>
                        <pre class="alt"><span class="lnum"> 271:  </span>                    street.val(obj.name);</pre>
                        <pre><span class="lnum"> 272:  </span>                    street.data( <span class="str">"kladr-obj"</span>, obj );</pre>
                        <pre class="alt"><span class="lnum"> 273:  </span>                    street.parent().find( <span class="str">'label'</span> ).text( obj.type );</pre>
                        <pre><span class="lnum"> 274:  </span>                    building.kladr( <span class="str">'option'</span>, { parentType: $.ui.kladrObjectType.STREET, parentId:  obj.id } );</pre>
                        <pre class="alt"><span class="lnum"> 275:  </span>                    Log(obj);</pre>
                        <pre><span class="lnum"> 276:  </span>                    AddressUpdate();</pre>
                        <pre class="alt"><span class="lnum"> 277:  </span>                    MapUpdate(); </pre>
                        <pre><span class="lnum"> 278:  </span>                }              </pre>
                        <pre class="alt"><span class="lnum"> 279:  </span>            });</pre>
                        <pre><span class="lnum"> 280:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 281:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 282:  </span>        building.change(<span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum"> 283:  </span>            <span class="kwrd">var</span> query = {</pre>
                        <pre><span class="lnum"> 284:  </span>                token: token,</pre>
                        <pre class="alt"><span class="lnum"> 285:  </span>                key: key,</pre>
                        <pre><span class="lnum"> 286:  </span>                value: building.val(),</pre>
                        <pre class="alt"><span class="lnum"> 287:  </span>                type: $.ui.kladrObjectType.BUILDING,</pre>
                        <pre><span class="lnum"> 288:  </span>            };</pre>
                        <pre class="alt"><span class="lnum"> 289:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 290:  </span>            <span class="kwrd">var</span> cityObj = city.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre class="alt"><span class="lnum"> 291:  </span>            <span class="kwrd">if</span>(cityObj){</pre>
                        <pre><span class="lnum"> 292:  </span>                query[<span class="str">'parentType'</span>] = $.ui.kladrObjectType.CITY;</pre>
                        <pre class="alt"><span class="lnum"> 293:  </span>                query[<span class="str">'parentId'</span>] = cityObj.id;</pre>
                        <pre><span class="lnum"> 294:  </span>            } </pre>
                        <pre class="alt"><span class="lnum"> 295:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 296:  </span>            <span class="kwrd">var</span> streetObj = street.data( <span class="str">"kladr-obj"</span> );</pre>
                        <pre class="alt"><span class="lnum"> 297:  </span>            <span class="kwrd">if</span>(streetObj){</pre>
                        <pre><span class="lnum"> 298:  </span>                query[<span class="str">'parentType'</span>] = $.ui.kladrObjectType.STREET;</pre>
                        <pre class="alt"><span class="lnum"> 299:  </span>                query[<span class="str">'parentId'</span>] = streetObj.id;</pre>
                        <pre><span class="lnum"> 300:  </span>            }            </pre>
                        <pre class="alt"><span class="lnum"> 301:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 302:  </span>            $.kladrCheck(query, <span class="kwrd">function</span>(obj){</pre>
                        <pre class="alt"><span class="lnum"> 303:  </span>                <span class="kwrd">if</span>(!obj) {</pre>
                        <pre><span class="lnum"> 304:  </span>                    building.css(<span class="str">'color'</span>, <span class="str">'red'</span>);</pre>
                        <pre class="alt"><span class="lnum"> 305:  </span>                } <span class="kwrd">else</span> {</pre>
                        <pre><span class="lnum"> 306:  </span>                    building.val(obj.name);</pre>
                        <pre class="alt"><span class="lnum"> 307:  </span>                    building.data( <span class="str">"kladr-obj"</span>, obj );</pre>
                        <pre><span class="lnum"> 308:  </span>                    Log(obj);</pre>
                        <pre class="alt"><span class="lnum"> 309:  </span>                    AddressUpdate();</pre>
                        <pre><span class="lnum"> 310:  </span>                    MapUpdate(); </pre>
                        <pre class="alt"><span class="lnum"> 311:  </span>                }              </pre>
                        <pre><span class="lnum"> 312:  </span>            });</pre>
                        <pre class="alt"><span class="lnum"> 313:  </span>        });</pre>
                        <pre><span class="lnum"> 314:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 315:  </span>        $(<span class="str">'[name="building-add"]'</span>).change(<span class="kwrd">function</span>(){</pre>
                        <pre><span class="lnum"> 316:  </span>            AddressUpdate();</pre>
                        <pre class="alt"><span class="lnum"> 317:  </span>            MapUpdate(); </pre>
                        <pre><span class="lnum"> 318:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 319:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 320:  </span>        <span class="kwrd">var</span> fields = city.add(street).add(building).add(buildingAdd);</pre>
                        <pre class="alt"><span class="lnum"> 321:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 322:  </span>        fields.keydown(<span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum"> 323:  </span>            $(<span class="kwrd">this</span>).css(<span class="str">'color'</span>, <span class="str">'black'</span>);</pre>
                        <pre><span class="lnum"> 324:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 325:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 326:  </span>        fields.bind(<span class="str">'downloadStart'</span>, <span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum"> 327:  </span>            $(<span class="kwrd">this</span>).parent().find(<span class="str">'.spinner'</span>).show();</pre>
                        <pre><span class="lnum"> 328:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 329:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 330:  </span>        fields.bind(<span class="str">'downloadStop'</span>, <span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum"> 331:  </span>            $(<span class="kwrd">this</span>).parent().find(<span class="str">'.spinner'</span>).hide();</pre>
                        <pre><span class="lnum"> 332:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 333:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 334:  </span>        ymaps.ready(<span class="kwrd">function</span>(){</pre>
                        <pre class="alt"><span class="lnum"> 335:  </span>            <span class="kwrd">if</span>(map_created) <span class="kwrd">return</span>;</pre>
                        <pre><span class="lnum"> 336:  </span>            map_created = <span class="kwrd">true</span>;</pre>
                        <pre class="alt"><span class="lnum"> 337:  </span>&nbsp;</pre>
                        <pre><span class="lnum"> 338:  </span>            map = <span class="kwrd">new</span> ymaps.Map(<span class="str">'map'</span>, {</pre>
                        <pre class="alt"><span class="lnum"> 339:  </span>                center: [<span class="str">55</span>.<span class="str">76</span>, <span class="str">37</span>.<span class="str">64</span>],</pre>
                        <pre><span class="lnum"> 340:  </span>                zoom: <span class="str">12</span></pre>
                        <pre class="alt"><span class="lnum"> 341:  </span>            });</pre>
                        <pre><span class="lnum"> 342:  </span>&nbsp;</pre>
                        <pre class="alt"><span class="lnum"> 343:  </span>            map.controls.add(<span class="str">'smallZoomControl'</span>, { top: <span class="str">5</span>, left: <span class="str">5</span> });</pre>
                        <pre><span class="lnum"> 344:  </span>        });</pre>
                        <pre class="alt"><span class="lnum"> 345:  </span>    });</pre>
                        <pre><span class="lnum"> 346:  </span>})(jQuery); </pre>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>