<?php

 use \Phalcon\Tag ?>


<script>
    var crc = [];
<?php
$prices = array(400, 1000);
foreach ($prices as $price)
{
    $crc = md5($this->config->options->login . ':' .
	    $price . '.00:' .
	    ':' .
	    $this->config->options->password);
    echo "crc[$price] = '$crc'; \n";
}
?>

    var processPayment = function(price){
	$('#OutSum').val(price + '.00');
	$('#SignatureValue').val(crc[price]);
	
	$('#pay-form').submit();
    }

</script>

<form action='https://merchant.roboxchange.com/Index.aspx' method="POST" id="pay-form">
    <input type="hidden" name="MrchLogin" value="<?= $this->config->options->login ?>">
    <input type="hidden" name="OutSum" value="" id="OutSum">
    <input type="hidden" name="InvId" value="">
    <input type="hidden" name="SignatureValue" value="" id="SignatureValue">
    <input type="hidden" name="IncCurrLabel" value="rub">
    <input type="hidden" name="Culture" value='ru'>
</form>

<div class="content">
    <div class="cBlock" style="min-height: 500px;">
	<div class="contentMain">
	    <h1>Регистрация</h1>
	    <p>Для начала работы с сервисом вам необходимо зарегистрироваться. После регистрации вы получите персональный токен.</p>
	    <?= $this->getContent() ?>
            <div class="form">
		<form action="/register" method="post">   
		    <?= Tag::textField(array("email", "id" => "inputEmail", "placeholder" => "Ваш e-mail", "data-email" => "y")) ?>
		    <div class="checkbox">
			<?= Tag::checkField(array("accept", "id" => "accept", "value" => "y")) ?>
			<label for="accept">Согласен с <a href="/prices/#conditions" target="_blank">условиями использования сервиса</a></label> 
		    </div>
		    <?= Tag::submitButton(array('Регистрация', "class" => "btn")) ?>
		</form>
            </div>
	    <br><br><br><br>
	    <h1>Коммерческое использование</h1>
	    <p>
		Если Вам необходимо интегрировать сервис в Ваш тиражируемый коммерческий продукт, 
		или Вы хотите получить 100% гарантию работы сервиса подтвержденную договорными условиями.
		</a>
	    </p>
	    <b>Особенности платной версии:</b>
	    <ul class="ul-list">
		<li>Гарантия работы сервиса, отдельные сервера (http://kladr-api.com/api.php).</li>
		<li>Помощь в настройке по скайпу, ответ технической поддержки в течение рабочего дня.</li>
		<li>Возможность установить решение на Ваши сервера.</li>
		<li>Скидки для реселлеров и разработчиков.</li>
	    </ul>
		<br>
		<a href="/business">Узнать подробности</a>



    </div>
</div>