<?php

use \Phalcon\Tag ?>


<script>
    var crc = [];
<?php
$prices = array(900, 1400, 1500, 2000, 3000, 30000, 10000);
foreach ($prices as $price)
{
    $crc = md5($this->config->options->login . ':' .
            $price . '.00:' .
            ':' .
            $this->config->options->password);
    echo "crc[$price] = '$crc'; \n";
}

// TODO: убрать из шаблона в контроллер
$discount = $this->config->options->coupon == (isset($_REQUEST['coupon']) ? $_REQUEST['coupon'] : '');
?>

    var processPayment = function (price) {
        $('#OutSum').val(price + '.00');
        $('#SignatureValue').val(crc[price]);

        $('#pay-form').submit();
    }

</script>

<form action='https://merchant.roboxchange.com/Index.aspx' method="POST" id="pay-form">
    <input type="hidden" name="MrchLogin" value="<?= $this->config->options->login ?>">
    <input type="hidden" name="OutSum" value="" id="OutSum">
    <input type="hidden" name="InvId" value="">
    <input type="hidden" name="SignatureValue" value="" id="SignatureValue">
    <input type="hidden" name="IncCurrLabel" value="rub">
    <input type="hidden" name="Culture" value='ru'>
</form>

<div class="content">
    <div class="cBlock" style="min-height: 500px;">
        <div class="contentMain">
            <h1>Регистрация на серверах с гарантированной работой</h1>
            <p>
                Для бизнеса и интернет-магазинов — 100% гарантия работы сервиса подтвержденная договорными условиями.<br>Помощь в настройке и техническая поддержка.
                </a>
            </p>

            <style>
                .ratesBlock {
                    width: 685px;
                    height: 344px;
                    border: 3px solid #EFEFEF;
                    position: relative;
                    margin: 30px 0 0;
                    padding: 0 20px;
                }		

                .ratesBlock .middleSide {
                    position: absolute;
                    left: 0;
                    right: 0;
                    margin: auto;
                    top: 0px;
                    z-index: 3;
                    height: 344px;
                    width: 218px;
                    border: 3px solid #EFEFEF;
                    background: white;
                    padding: 0 20px;
                    border-top: none;
                    border-bottom: none;
                }

                .ratesBlock .middleSide h2 {
                    padding-top: 30px;
                    font-size: 24px;
                }	

                .ratesBlock .middleSide .button {
                    width: 185px;
                    height: 32px;
                    line-height: 32px;
                    margin: 15px auto 0;
                    font-size: 18px; 
                    box-shadow: 0 1px 0 #B85D02;
                }	

                .desc p{
                    font-size:15px;
                    padding:0px !important;
                }

                .ratesBlock .eastSide {
                    float: right;
                    width: 184px;
                    position: relative;
                }

                .ratesBlock .desc {
                    height: 120px;
                    margin-top: 20px;
                }		
            </style>


            <?php if ($discount): ?>

                <div class="ratesBlock">
                    <div class="westSide" >
                        <h2>Тестовый</h2>
                        <h3>900 руб. <br>на 3 месяца</h3>

                        <div class="desc">
                            <p>Позволяет проверить коммерческие сервера.</p>
                        </div>
                        <a href="javascript: processPayment(900)" class="button">Подключить</a>
                    </div>
                    <div class="middleSide">
                        <div class="rel">
                            <h2>Для физ. лиц</h2>
                            <h3>1500 руб. <br>на 1 год</h3>
                            <div class="desc">
                                <p>Работаем на основе <a href="https://drive.google.com/file/d/0B0sSPtvPGc3HdjlHejg0Z2RKU2s/view?usp=sharing">договора оферты</a>.</p>
                            </div>
                            <a href="javascript: processPayment(1500)"  class="button">Подключить</a>
                        </div>
                    </div>
                    <div class="eastSide">
                        <h2>Для юр. лиц</h2>
                        <h3>5000 руб. <br>на 1 год</h3>
                        <div class="desc">
                            <p>Заключаем договор с юр. лицом, выставляем счета, акты, высылаем оригиналы по почте.</p>
                        </div>
                        <a href="/business/#bill" class="button">Подключить</a>
                    </div>
                    <div class="ratesShadow"></div>
                </div>         
            <?php else: ?>
                <div class="ratesBlock">
                    <div class="westSide" >
                        <h2>Тестовый</h2>
                        <h3>1400 руб. <br>на 3 месяца</h3>


                        <div class="desc">
                            <p>Позволяет проверить коммерческие сервера.</p>
                        </div>
                        <a href="javascript: processPayment(1400)" class="button">Подключить</a>
                    </div>
                    <div class="middleSide">
                        <div class="rel">
                            <h2>Для физ. лиц</h2>
                            <h3>2000 руб. <br>на 1 год</h3>

                            <div class="desc">
                                <p>Работаем на основе <a href="https://drive.google.com/file/d/0B0sSPtvPGc3HdjlHejg0Z2RKU2s/view?usp=sharing">договора оферты</a>.</p>
                            </div>
                            <a href="javascript: processPayment(2000)"  class="button">Подключить</a>
                        </div>
                    </div>
                    <div class="eastSide">
                        <h2>Для юр. лиц</h2>
                        <h3>5000 руб. <br>на 1 год</h3>
                        <div class="desc">
                            <p>Заключаем договор с юр. лицом, выставляем счета, акты, высылаем оригиналы по почте.</p>
                        </div>
                        <a href="/business/#bill" class="button">Подключить</a>
                    </div>
                    <div class="ratesShadow"></div>
                </div> 

            <?php endif ?>


            <br><br><br><br><br><br>
            <h1>Регистрация на бесплатных серверах</h1>
            <p>Сервисом можно пользоваться бесплатно.<br> Мы не несем обязательств по стабильной работе публичных серверов, а так же не гарантируем техническую поддержку по вопросам внедрения «Кладра в облаке». 
                При этом мы безусловно следим за работой публичных серверов в меру наших возможностей.
            </p>
            <?= $this->getContent() ?>
            <div class="form">
                <form action="/register" method="post">   
                    <?= Tag::textField(array("email", "id" => "inputEmail", "placeholder" => "Логин", "data-email" => "y")) ?>
                    <div class="checkbox">
                        <?= Tag::checkField(array("accept", "id" => "accept", "value" => "y")) ?>
                        <label for="accept">Согласен с <a href="/prices/#conditions" target="_blank">условиями использования сервиса</a></label> 
                    </div>
                    <?= Tag::submitButton(array('Регистрация', "class" => "btn")) ?>
                </form>
            </div>
            <br><br>
            <a href="http://passwork.ru" target="_blank">
                <img src="https://passwork.me/b/passwork_02_ru.png" style="width: 200px; margin: 0px" >
            </a>            


            <br><br><br><br><br><br>
            <br><br><br><br><br><br>


        </div>
    </div>