<?php

 use Phalcon\Tag; ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="keywords" content="<?= $keywords ?>">
        <meta name="description" content="<?= $description ?>">

	<?= Tag::getTitle() ?>

	<?= Tag::stylesheetLink('css/style.css'); ?>

<?= Tag::javascriptInclude('js/jquery-1.8.3.min.js'); ?>
<?= Tag::javascriptInclude('js/responsiveslides.js'); ?>
	<script>
	    $(document).ready(function(){
		$('.rSlide').responsiveSlides({
		    auto: false,
		    speed: 500,
		    timeout:4000,
		    pager: true,
		    pause:true,
		    nav: false,
		    manualControls:".pager"
		});
	    });
	</script>	
    </head>
    <body>
	<div class="page">
	    <?php $this->partial('partials/header'); ?>
	    <?= $this->getContent() ?>
	    <?php $this->partial('partials/footer'); ?>

<?php $this->partial('partials/google_analytics'); ?>
<?php $this->partial('partials/reformal'); ?>
	</div>

    </body>
</html>




